### ISSUE TITLE
Epic: Get all TransDim calendars working

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1012]
**DONE**

- [x] #1129
- [x] Tribe Events? https://spectra-london.org.uk/all-events/. Done with webcal link.
- [x] Indicate that we can import webcal:// addresses
- [x] Feedback when importer has encountered an error could be more helpful (i think mgiht be when importer is already running?)
- [x] #1205
- [x] #1201
- [x] #1202
- [x] #1207
- [x] London Friend use Simple Calendar, looks like a WP plugin. Possibly fed by GoogleCal. https://londonfriend.org.uk/calendar/

**WONTFIX**

- [x] Some custom wordpress plugin https://www.transradiouk.com/show-schedule/. Not bothering with this for MVP at least.

**Stuff to work on**

- [x] #1198
- [x] #1221
- [x] #1220

**Comment by kimadactyl** [comment]
Spectra isn't importing properly. They have a [link on their website](https://spectra-london.org.uk/all-events/) for which the most promising link looks like this webcal one

webcal://spectra-london.org.uk/?post_type=tribe_events&tribe-bar-date=2022-04-17&ical=1

if you add to google calendar you get this, which doesnt work

https://calendar.google.com/calendar/ical/hc76bl2it203re29ftr47v15t2fnbr3l%40import.calendar.google.com/public/basic.ics

i think this is just a whitelist issue and we shuold support the webcal address

**Comment by kimadactyl** [comment]
Moved Facebook items to #1130
