### ISSUE TITLE
Epic: fix JavaScript tech debt

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1151]
**Is your feature request related to a problem? Please describe.**

Currently we have a mess of JS stuff: some vanilla, some JQuery, some Vue. Our webpacker config is overcomplex and is deperecated in Rails 7. This is really holding the app back in terms of maintanability, understandability, etc.

We need to pull out Webpacker, and [migrate to jsbundling-rails](https://github.com/rails/jsbundling-rails).

**Describe the solution you'd like**

- [x] Walk back to repo to Rails 6, re-open the closed Rails 6 bump PR, and upgrade the Ruby version in it to 2.7.6 (this was a mistake). This will at least get us to most up to date rails 6 / ruby 2.7 etc.
- [x] #1158
- [x] Add Stimulus/Turbo and remove `turbolinks`
- [x] Update project README with info on how to run the node server etc
- [x] Set up jQuery loader possibly using `expose-loader` so we can use our existing Datatables code, for now
- [x] Ensure all JS works (datatables for e.g.), and maybe add some tests for this. If this is a pain maybe we can just make something from scratch in stimulus
- [x] ~~Replace the vue.js datepicker with one made in Stimulus/Turbo~~ just get vue working
- [x] Clean up package.json and check that webpacker is firmly gone
- [x] Get it deploying on Staging and running properly etc
- [x] Get it deploying on Prod
