### ISSUE TITLE
Basic support for multi-day events

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1207]
## User story

As a partner I need to list multi day events on my calendar so that i can put on festivals and the like

## Acceptance criteria

- [x] My multi-day events get imported into PlaceCal
- [x] On *.placecal.org/events, multi-day events just show up based on the first day
- [x] On *.placecal.org/partner/x, multi-day events just show up based on the first day
- [x] The LGBT consortium multi-day events import
- [x] Create another ticket handling showing multi-day events that have already started

## Implementation notes & questions

* Part of this is an importer problem
* Part of it is a frontend query issue
* Also consider graphQL
* [Sample feed](https://www.consortium.lgbt/events/?ical=1)

## Implementation plan

What Calendar is "LGBT consortium" part of?

Look at the code in `app/jobs/calendar_importer/` to remove the one day limit.
Look at events controller index action
Look at partner controller show action
Look at the c data set (partner id=135 on production/staging) to find multi-day events and where they are being skipped, part of "PlaceCal London" and "The Trans Dimension" sites
Make modifications to importer and controllers
Verify that multi-day events are being imported
Tests for importer and controllers (where appropriate)
