### ISSUE TITLE
Add a "no location" strategy to calendars

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1210]
## User story

As a calendar admin I need to be able to add a calendar and have the location field ignored, so that things that are not in a set or geo-locatable location, or where the location is secret, can be added to PlaceCal

## Acceptance criteria

- [ ] I can add a calendar feed with events that have no information in the location field and have the events import into PlaceCal
- [ ] I can add a calendar feed with events that have a known location in the location field and have the events import into PlaceCal with the location not set
- [ ] In both of these cases, the event does not raise a notice
- [ ] The events show up on the partner page
- [ ] The events show up on the *.placecal.org/events page

## Implementation notes & questions

Propose adding a "no location" strategy

## Implementation plan

_To be written by the developer_
