### ISSUE TITLE
Allow for relationships between partners

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1216]
## User story

As an organisation with multiple venues or subgroups and campaigns, I need to be able to show the connections between them explicitly so that people can see all of it's connected

## Acceptance criteria

- [ ] Partners can have child and parent relationships to other partners
- [ ] Partners with children have a different kind of page that lists all the children
- [ ] Partners with parents shows easy links back to the parent
- [ ] more tbc...

## Implementation notes & questions

This is partly implemented already in the database, we just don't have an interface for it

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
LC also suggested this could be good for funders to indicate who they have given grants to and is poss a prereq for #1215
