### ISSUE TITLE
Add caching to key pages

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1234]
## User story

As a citizen I need PlaceCal to load quickly so that I don't get bored or think PlaceCal is broken or low quality.

As a director of PHT I want to keep our hosting costs down in order that we save money to spend on other things.

## Acceptance criteria

- [ ] `/partners` page is cached
- [ ] `/events` page is cached
- [ ] Other pages are reviewed for performance

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
delegated to appsignal
