### ISSUE TITLE
Event view for partners with no or few events is confusing

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1306]
## User story

1. As a resident I need to be able to see if partners have no calendar connected so that I don't just assume there are no events
1. As a resident I need to be able to see if partners have no upcoming events so that I know I can check back later and find out
1. As a resident I need to be able to see the next few upcoming events for partners who only put a few things on, so that I can see they do indeed have events without clicking around for ages

## Acceptance criteria

- [x] Partners with no calendars connected have no "events" section on their page and say something like "this partner does not list their events on placecal - try their website or social media"
- [x] Partners with a calendar connected and no upcoming events have no "events" section and say "no upcoming events"
- [x] Partners with less than 10 upcoming events are presented in a simple list rather than using the week picker
- [x] Partners with more than 10 upcoming events have the week picker but the next upcoming event is selected, OR we move to simple pagination

## Implementation notes & questions

Can fix #1307 while we're here

## Implementation plan

1. Check how many future events the controller wants to load for the partner view page
2. Load a different component depending on the upcoming event count
