### ISSUE TITLE
Migrate CSS to cssbundling-rails

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1319]
## User story

As a developer, I want all the CSS in one place and using a modern build process, in order that things compile quickly, its easy to know where to look for code, and we can use variables and mixins properly.

https://github.com/rails/cssbundling-rails

## Acceptance criteria

- [x] CSS all moved out of mountain view and main sprockets directory into a nice clean area
- [ ] CSS built by a sep process in the Procfile
- [ ] CSS structure is well documented and directory structure and inheritance easy to understand
- [ ] Mountain View doesnt complain about missing assets (bonus round - maybe out of scope)
 
## Implementation notes & questions

I think we use Dart Sass for this out of the listed options but I don't really understand them?

Variables and mixins need including in each file individually atm - its not the worst and doesnt impact actual performance but its a bad smell. Hopefully this removes the need for that.

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
with hindsight i am a bit worried this was an old kim busywork "feels really nice but doesnt actually acheive much" job but i think itd be nice. deprecating mountain_view feels more important, assume youre already on that tho. up to you obvi but yeah its funny with distance how things you thought were completely needed are perhaps not.

dont get me wrong there are some real pros to it. i think its nice to just use native node tools to do the frontend stuff, it makes a cleaner sep of concerns in the applicaiton structure, it  means you can have proper console output for sass errors bc of how Procfile thingy works, and i think it makes it easier to swap sass compliation library in the future. poss other beenfits too

but yeah. like How Important Are Those Things?

**Comment by katjam** [comment]
> **proposal** we switch to `cssbundling-rails` once the last mountain_view component is gone, this will then be a small ticket.

Sounds like a good plan. Shall we mark as blocked until then?

**Comment by kimadactyl** [comment]
Asking around people do seem very keen on Tailwind and i think it would make the component logic, themeing etc a lot simpler.

Possibly this makes sense to do as part of #1812 

This is comptible with cssbundling-rails but there may be other ways to do this.

**Comment by kimadactyl** [comment]
I am gonna close this as I think the thinking here is very stale and the functionality needs re-deciding from first principles.
