### ISSUE TITLE
News should show up in the main navigation if there are news articles for the current site

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1324]
## User story

As a citizen I need to see news that's happening in my neighbourhood so that I can find out what's going on.

## Acceptance criteria

- [x] If there's at least one news article for my current site, show a link to https://{sitename}.placecal-staging.org/news in the main navigation
- [ ] News index page shows title, date, partner who published the piece
- [ ] News show page shows all the above plus date and author
- [ ] Tidy up the CSS for the index page
- [ ] Tidy up the CSS for the show page

## Implementation plan

- [ ] look at navigation partial
- [ ] check to see if news items can be found through site
- [ ] post some news articles in partners on a site and see if they turn up
- [ ] investigate why this is not happening if it fails

**Comment by katjam** [comment]
@ivankocienski Which site is the one with news so I can test this?
