### ISSUE TITLE
It is unclear how contact info on a calendar and contact info on a partner are used

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1338]
## User story

As a user who can edit partner details and add calendars I need know how the contact info from the 2 forms (partner vs calendar) is used so that I understand which info to put there,

## Acceptance criteria

- [ ] Change calendar public contact info help text to "the contact info for the email account that manages this calendar"
- [ ] Remove partnership contact info

## Implementation notes & questions
![image](https://user-images.githubusercontent.com/861172/174607993-e2fc7dae-6f5f-4173-a316-a4efc3f30197.png)
![image](https://user-images.githubusercontent.com/861172/174608055-5a50407e-6537-419e-8fe9-d096d2bbbcef.png)

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Related to #1017

**Comment by ivankocienski** [comment]
This seems to me to have a lot of copy that needs writing for the help text. 

Apparently the address as shown on Partners and Events both come from the partner

[Partners](https://github.com/geeksforsocialchange/PlaceCal/blob/50b40d4f5dd71a68b944ea409e5f110df8d9b621/app/views/partners/show.html.erb#L30)

[Events](https://github.com/geeksforsocialchange/PlaceCal/blob/50b40d4f5dd71a68b944ea409e5f110df8d9b621/app/views/events/show.html.erb#L20)

you know- maybe the calendars contact details are not used at all

**Comment by kimadactyl** [comment]
@katjam and @ivankocienski  - opinions on if we either

1. turn the help text into "the contact info for the account that manages this calendar", and delete "partnership contact"
2. do 1, but do #1345 first

i think 1 on its own is fine for now?

**Comment by kimadactyl** [comment]
arg sorry im too hot. i think theres 2 user stories here:

1. something to do with members of the public reporting wrong events 
2. the placecal team knowing who to talk to about it

i dont think this changes anything but putting here for posterity

**Comment by katjam** [comment]
Agree help text will satisfy the acceptance here.

**Comment by kimadactyl** [comment]
Yes that sounds good. We got there in the end. I think the other one is

- [ ] Remove partnership contact info

I'll update the base ticket

**Comment by ivankocienski** [comment]
So the text has been changed on the admin 'show/edit calendar' page.

The partnership contact info has been removed from the 'edit calendar' page but also appears on the 'edit partner' page. should both parts be dropped?

And if dropped should the fields be removed from the DB and the code gone over to remove mention of this partnership info from the front end?

**Comment by kimadactyl** [comment]
> The partnership contact info has been removed from the 'edit calendar' page but also appears on the 'edit partner' page. should both parts be dropped?

These are different fields, leave the partner as is
 
> And if dropped should the fields be removed from the DB and the code gone over to remove mention of this partnership info from the front end?

The calendar fields should be dropped yeah

**Comment by katjam** [comment]
This still looks the same to me:
![image](https://user-images.githubusercontent.com/861172/182149475-673f95bd-95f3-4122-8c28-17d5944c976c.png)

**Comment by katjam** [comment]
Verified changes on calendar edit page... was:
![image](https://user-images.githubusercontent.com/861172/182149988-f7046118-3de9-41ca-b8f8-f77f04e8d08b.png)

Changed to:
![image](https://user-images.githubusercontent.com/861172/182150057-6323d2ba-8740-446f-a7a5-e917663feebd.png)

**Comment by kimadactyl** [comment]
That's correct. Partner should have two contacts.
