### ISSUE TITLE
Document and make tickets for all the javascript functionality we are using in the app

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1340]
## User story

**Scope update: lets close this when we are happy we have tickets open for all JS**

_As a developer, I don't want loads of weird unpredictable javascript hanging around because it is bad when the app crashes or does weird interface things._

We need to replace our current frankenstein system of jQuery, Vue etc with some nice modern stimulus/hotwire and stop having random js dotted throughout the app. Or at least, get it working properly without loads of weird workarounds and stuff that breaks when you press the back button.

The first step for this is to list out everything it currently does and then make tickets for all the items.

We poss need to do this separately for frontend and backend.

## Features to make ticket sfor

- [x] Select2 multiselect (e.g. in edit calendar)
- [x] Select2 singleselect (e.g
- [x] Cocoon (e.g. in service areas in edit partner form)
- [x] Datatables (e.g. /partners listing)
- [x] Leaflet (e.g. frontend mapbox integration)
- [x] Opening times (e.g. partner edit page)
- [x] Autofill form fields
- [ ] ...?

## Implementation notes & questions

#870 is a prerequisite before starting anything
- Can we completely remove vue.js from the app? It's only the opening times picker using it.
- look through js directory and check if there is anything not in the list

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
I will start writing more in depth notes in the wiki because some of it will be for my understanding about the codebase and might need pruning later.

https://github.com/geeksforsocialchange/PlaceCal/wiki/JS-in-PC

**Comment by kimadactyl** [comment]
Scope update: lets close this when we are happy we have tickets open for all our js.

Have updated the base ticket.
