### ISSUE TITLE
Turn contact information into it own model that can be associated with different things

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1345]
## User story

As a partner, I want to be able to share contact info across the various partner and calendar options without loads of cut and pasting, to reduce confusion and duplication.

As an organiser, I want to reduce the amount of duplication of partner and calendar contact info I have, in order that the data is more reliable and I have to spent less time cut and pasting

As a partner or organiser, I want to be able to have more than one management contact, or none, and generally be able to more flexibly set contacts for partners

As a partner, I want to be able to update my contact info in my profile and have all my partners update automatically, so that all the info stays up to date

## Acceptance criteria

- [ ] Contact info can be a user profile link instead
- [ ] Partners must have one contact, but can have additional administrative and management contacts
- [ ] Calendars must have one contact, but can have additional administrative and management contacts
- [ ] When created, calendars copy adminiistrative info from the parent calendar
- [ ] All data is migrated into this new model

## Implementation plan

_To be written by the developer_
