### ISSUE TITLE
Detect bad language in content

### ISSUE THREAD

**Issue by ivankocienski** [geeksforsocialchange/PlaceCal#1350]
## User story

As a user of the site I would like to not see foul language on PlaceCal.

As a commissioner from a big institution I can't commission a service that doesn't have a swear filter.

Things like

- [ ] Article title, body, summary, slugs
- [ ] Event summary, description
- [ ] Partner names, descriptions, slugs
- [ ] etc...

## Implementation notes & questions

Not sure how much of a problem this will be for us but it would be prudent to at least consider the problem. This will be an open ended effort but as long as we stop people from doing the basics it may suffice.

## Implementation plan

Research foul language detection gems that hopefully exist or similar functionality in other languages. There may be a SaaS that we can push this onto.

...

**Comment by erbridge** [comment]
I think this is a thing we should steer clear of unless there's a ready-made solution we can drop in. Maintaining swear filters is a nightmare, and also opens up a big questions about what language is acceptable to who and what isn't. I suspect this needs a human approach, not a tech one, eg organisers spot / have reported to them unacceptable language in events and approach the partner about it, removing the partner from their area if necessary.

**Comment by kimadactyl** [comment]
I agree I would rather not implement this any time soon. Do you know if this is a barrier for e.g. gov.uk G-Cloud? (also wow they really named it exactly the same as google cloud huh)

The main time this happens is clubnights and band nights etc - I don't think it's happening maliciously but you know, people do have band names with swears in them for example.

**Comment by erbridge** [comment]
As far as I know, this is not a barrier for G-Cloud per se, though it might be a thing a client coming through G-Cloud might ask for. I suggest we then tackle it at the client site level (since a list like this would be very subjective anyway).
