### ISSUE TITLE
Remove old Facebook integration stuff

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1351]
Our old Facebook integration stuff is getting in the way and keeps causing me local authentication problems. It's also cluttering up the interface for users. We should scrub all this out the app in preparation for switching to Faceloader.

## Acceptance criteria

- [ ] Pull gems related to this
- [ ] Take out all buttons related to adding facebook calendars
- [ ] Delete database tables
- [ ] Update the example env file and secrets etc in the app
- [ ] Check we don't have any refs to it in our documentation

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
Verified on staging - some good facebook remains;
![image](https://user-images.githubusercontent.com/861172/181267197-a56fe5c8-27c4-4ed4-8bef-748377da3831.png)
![image](https://user-images.githubusercontent.com/861172/181268830-ef92e5c3-608a-4a45-a726-200461448b70.png)


Facebook events management gone:
![image](https://user-images.githubusercontent.com/861172/181267853-aee45b19-d70c-470c-8c78-4741fca4072a.png)

Gems removed: Crypt keeper & Koala
Data removed: Facebook App Id & Secret

**Comment by katjam** [comment]
@ivankocienski Am verifying stuff on staging - is this correct as it is?

![image](https://user-images.githubusercontent.com/861172/181269431-8a21597e-1817-48c5-87bd-35d6f23644c2.png)

**Comment by katjam** [comment]
@kimadactyl @ivankocienski It looks like notion docs still have some facebook mentions. I'm not sure what we want to offer as an alternative - who can rewrite this?
![image](https://user-images.githubusercontent.com/861172/181271197-5f9f7dcb-15fe-406d-a816-d2db3be3b6aa.png)

![image](https://user-images.githubusercontent.com/861172/181271266-ba764fb1-b12c-4d1f-af0c-a390dcede4b7.png)

**Comment by kimadactyl** [comment]
Guide page is correct! That's for Faceloader. Will update when Faceprox done :)
