### ISSUE TITLE
Partner admins can create more partner admin accounts for the same partner

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1366]
## User story

As a partner admin, I want to be able to create other partner admins for my partner, in order that we are not sharing logins.

## Acceptance criteria

- [ ] Partner admins can create another partner admin from their partner view page
- [ ] Partner admins can see other partner admins for their partner
- [ ] Partner admins cannot see other users
- [ ] Partner admins cannot create other types of user

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
I have a feeling this a an `eee` ticket and it's sort of livable so moving off this milestone
