### ISSUE TITLE
Support OutSavvy by implementing ld+json support

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1367]
## User story

As a partner using OutSavvy, I want my events to be imported into PlaceCal automatically, so I can get them listed without any extra effort

## Acceptance criteria

- [ ] Outsavvy event listings can be imported
- [x] ~README and example environement shows how to set it up - no longer needed~
- [ ] Draft handbook page is created

Current partners to support:

```
https://www.outsavvy.com/organiser/sappho-events
https://www.outsavvy.com/organiser/lez-events
```

## Implementation notes & questions

[They have an API](https://www.outsavvy.com/organiser/sappho-events) that requires an API key but implies it's global access once you're in. So at least we don't need per-user API keys for this.

I think it'll be easier to just use ld+json to scrape the pages we want though

## Implementation plan

- [ ] Figure out how to scrape ld+json from the page
- [ ] Make a new importer archetype for ld+json
- [ ] Add specific tweaks for this

**Comment by kimadactyl** [comment]
Tagging @GeorgieMcVicar if you see any more or have any comments to add

**Comment by GeorgieMcVicar** [comment]
Nothing to add really - I have encountered this site a few times though so I think it would be worth making it compatible for the long term.

**Comment by kimadactyl** [comment]
Had a look at this and the data is available as ld+json in the organiser page - this makes it a lot simpler I think? And it means this ticket becomes "support ld+json" which is a lot more generically useful.

E.g. [Sappho Events](https://www.outsavvy.com/organiser/sappho-events) has the following info:

```json
[
  {
    "@context": "http://schema.org",
    "@type": "VisualArtsEvent",
    "name": "Queer Board Game Group",
    "startDate": "2022-11-08T19:00:00",
    "endDate": "2022-11-08T21:00:00",
    "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
    "url": "https://www.outsavvy.com/event/10425/queer-board-game-group",
    "image": "https://cdn.outsavvy.com/events/20083d67-7231-40bb-8931-80eb06c2d074.png",
    "eventStatus": "http://schema.org/EventScheduled",
    "description": "Are you queer and do you love playing board games?  Sappho runs a monthly social event for playing board games, open to LGBTQIA+ women, trans and non-binary people.  We have multiple tables set up with games, ranging from quick and easy games to learn for newbies, to medium-length strategy board games. If you&#39;ve got a game you&#39;d love to bring and teach others to play, please bring it too, as we will have some spare tables for wildcard games on the night.  This will be a really friendly environment where we can enjoy playing games with other queers who love games as much as us.  Learn something new, or put a new strategy to the test, and make some new queer friends in the process.  Date: Tuesday 8 November 2022, 7-9pm Location: The Commons, Glass House, 118 Bethnal Green Road, London, E2 6DGCost: &#163;7 cover charge (please note that costs go towards paying our staff to host the evening, and towards buying new board games)",
    "location": {
      "@type": "Place",
      "name": "The Commons at Glass House",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "The Commons at Glass House, 118 Bethnal Green Road, London, E2 6DG",
        "addressLocality": "London",
        "addressRegion": "England",
        "postalCode": "E2 6DG"
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "51.52462",
        "longitude": "-0.0720284"
      }
    },
    "offers": {
      "@type": "AggregateOffer",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2022-09-13T20:27:04",
      "priceCurrency": "GBP",
      "url": "https://www.outsavvy.com/event/10425/queer-board-game-group",
      "lowPrice": 7,
      "highPrice": 7,
      "availabilityStarts": "2022-11-08T20:59:00",
      "offers": [
        {
          "availability": "http://schema.org/InStock",
          "availabilityEnds": "2022-11-08T20:59:00",
          "name": "General Admission",
          "priceCurrency": "GBP",
          "url": "https://www.outsavvy.com/event/10425/queer-board-game-group",
          "price": 7,
          "availabilityStarts": "2022-09-13T20:27:04",
          "validFrom": "2022-09-13T20:27:04",
          "@type": "Offer"
        }
      ]
    },
    "performer": {
      "@type": "Organization",
      "url": "https://www.outsavvy.com/organiser/sappho-events",
      "description": "Sappho Events produces events for LGBTQ women and non-binary people in the UK. Our events revolve around common interest activities with a coffee and chat vibe. Our social events encourage making new friends and forming connections with other queer people. We also run dating events for queer women and non-binary people, which will be clearly marked.",
      "name": "Sappho Events"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "VisualArtsEvent",
    "name": "Queer Pottery Making Workshop (In Person, London)",
    "startDate": "2022-11-15T19:30:00",
    "endDate": "2022-11-15T21:00:00",
    "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
    "url": "https://www.outsavvy.com/event/10440/queer-pottery-making-workshop-in-person-london",
    "image": "https://cdn.outsavvy.com/events/ba517a36-0579-4f74-8d09-4f5f2299ee4e.png",
    "eventStatus": "http://schema.org/EventScheduled",
    "description": "Join Sappho Events for a relaxing pottery workshop led by artist Megan Elliott, focusing on traditional hand-building techniques using minimal tools.Date: 15 November, 7:30-9pmLocation: The Common Press, Glass House, London (118 Bethnal Green Road, London, E2 6DG). The nearest station is Shoreditch High Street OvergroundPrice: &#163;30 (you will take home 1-2 new clay creations. )Please note that this event is fully wheelchair accessible, including accessible bathrooms. Participants will learn how to make a pinch pot and a coil pot out of air-drying clay and will be guided through how to personalise their new creations.At the end of the class, participants should have two small finished pots to take away with them and tips on how to decorate these at home when dry. These pots are perfect as little storage vessels or ornaments and can also be used for succulents/small plants.No experience necessary - suitable for all levels. Your clay will still be delicate upon completion, so please bring a little box or container to carry your creations home. A cardboard box (approximately 15cm x 15cm is ideal), but we will also have newspaper to wrap them in if needed.Sappho Events welcomes LGBTQIA+ women, trans and non-binary people to our events",
    "location": {
      "@type": "Place",
      "name": "The Common Press at Glass House",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "The Common Press at Glass House, 118 Bethnal Green Road, London, E2 6DG",
        "addressLocality": "London",
        "addressRegion": "England",
        "postalCode": "E2 6DG"
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "51.52462",
        "longitude": "-0.0720284"
      }
    },
    "offers": {
      "@type": "AggregateOffer",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2022-09-14T16:48:40",
      "priceCurrency": "GBP",
      "url": "https://www.outsavvy.com/event/10440/queer-pottery-making-workshop-in-person-london",
      "lowPrice": 30,
      "highPrice": 30,
      "availabilityStarts": "2022-11-15T20:59:00",
      "offers": [
        {
          "availability": "http://schema.org/InStock",
          "availabilityEnds": "2022-11-15T20:59:00",
          "name": "General Admission",
          "priceCurrency": "GBP",
          "url": "https://www.outsavvy.com/event/10440/queer-pottery-making-workshop-in-person-london",
          "price": 30,
          "availabilityStarts": "2022-09-14T16:48:40",
          "validFrom": "2022-09-14T16:48:40",
          "@type": "Offer"
        }
      ]
    },
    "performer": {
      "@type": "Organization",
      "url": "https://www.outsavvy.com/organiser/sappho-events",
      "description": "Sappho Events produces events for LGBTQ women and non-binary people in the UK. Our events revolve around common interest activities with a coffee and chat vibe. Our social events encourage making new friends and forming connections with other queer people. We also run dating events for queer women and non-binary people, which will be clearly marked.",
      "name": "Sappho Events"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "Event",
    "name": "Queer Poetry Spoken Word Open-Mic Night - London",
    "startDate": "2022-11-17T19:00:00",
    "endDate": "2022-11-17T20:00:00",
    "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
    "url": "https://www.outsavvy.com/event/10450/queer-poetry-spoken-word-open-mic-night-london",
    "image": "https://cdn.outsavvy.com/events/def77413-ec77-4605-8c6b-dd51acbaca27.png",
    "eventStatus": "http://schema.org/EventScheduled",
    "description": "Join Sappho Events for an inspiring evening of queer spoken word poetry at Glass House, London&#39;s newest LGBTQIA+ venue in Shoreditch. On the night we will have a few established queer poets perform their work, alongside an open-mic line-up of new and emerging artists. This event is meant to give queer poets a chance to get back on stage and perform their work live for an audience. After so long staying at home during the pandemic, we hope to encourage people to try out new work, and maybe even try live performance for the first time. We also encourage acoustic singer-songwriters to perform their work on the evening. Performers will each have a 5-10 minute set, with timed slots handed out on the evening from 6:30pm. Please arrive before 7pm to reserve your spot, but we also welcome those who spontaneously decide on the night to perform in the second half of the evening. Date: Thursday 17 November, 7-8pmLocation: The Commons, Glass House, London (118 Bethnal Green Road, London, E2 6DG). The nearest station is Shoreditch High Street OvergroundPrice: &#163;10 entryOur event welcomes LBGTQIA+ women, trans and non-binary people. Please note the venue we are using for open mic is accessible, with accessible toilet access.",
    "location": {
      "@type": "Place",
      "name": "Common Counter at Glass House",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "Common Counter at Glass House, 118 Bethnal Green Road, London, E2 6DG",
        "addressLocality": "London",
        "addressRegion": "England",
        "postalCode": "E2 6DG"
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "51.52473",
        "longitude": "-0.0717826"
      }
    },
    "offers": {
      "@type": "AggregateOffer",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2022-09-14T17:46:39",
      "priceCurrency": "GBP",
      "url": "https://www.outsavvy.com/event/10450/queer-poetry-spoken-word-open-mic-night-london",
      "lowPrice": 10,
      "highPrice": 10,
      "availabilityStarts": "2022-11-17T19:59:00",
      "offers": [
        {
          "availability": "http://schema.org/InStock",
          "availabilityEnds": "2022-11-17T19:59:00",
          "name": "General Admission",
          "priceCurrency": "GBP",
          "url": "https://www.outsavvy.com/event/10450/queer-poetry-spoken-word-open-mic-night-london",
          "price": 10,
          "availabilityStarts": "2022-09-14T17:46:39",
          "validFrom": "2022-09-14T17:46:39",
          "@type": "Offer"
        }
      ]
    },
    "performer": {
      "@type": "Organization",
      "url": "https://www.outsavvy.com/organiser/sappho-events",
      "description": "Sappho Events produces events for LGBTQ women and non-binary people in the UK. Our events revolve around common interest activities with a coffee and chat vibe. Our social events encourage making new friends and forming connections with other queer people. We also run dating events for queer women and non-binary people, which will be clearly marked.",
      "name": "Sappho Events"
    }
  },
  {
    "@context": "http://schema.org",
    "@type": "VisualArtsEvent",
    "name": "Queer Book Club - London",
    "startDate": "2022-11-22T19:00:00",
    "endDate": "2022-11-22T20:00:00",
    "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
    "url": "https://www.outsavvy.com/event/10444/queer-book-club-london",
    "image": "https://cdn.outsavvy.com/events/228f8440-632d-4fe0-ad2d-8d02452fd3ff.png",
    "eventStatus": "http://schema.org/EventScheduled",
    "description": "Calling all queer book-lovers - join us for an evening of sapphic bookish chats. Every month, we will be reading a new piece of sapphic literature and coming together at @glasshouselondon to discuss over a cuppa or mocktail with the Sappho Events community.For November, we have chosen Torrey Peters&#39; novel, “Detransition, Baby”.Our friends at the Common Counter Press at Glass House will be kindly stocking copies for you to purchase ahead of the book club meeting. Tell them you’re buying the book for Sappho’s book club and you’ll receive a 10% discount. If you can&#39;t physically pick it up, they can post it to you (+ &#163;2.80 for postage) by emailing books@glasshouse.london.Date: Tuesday 22 November, 7-8pmLocation: The Common Press, Glass House, London (118 Bethnal Green Road, London, E2 6DG). The nearest station is Shoreditch High Street OvergroundPrice: &#163;6Please note that Sappho Events welcomes LGBTQIA+ women, trans and non-binary people. x",
    "location": {
      "@type": "Place",
      "name": "The Common Counter at Glass House",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "The Common Counter at Glass House, 118 Bethnal Green Road, London, E2 6DG",
        "addressLocality": "London",
        "addressRegion": "England",
        "postalCode": "E2 6DG"
      },
      "geo": {
        "@type": "GeoCoordinates",
        "latitude": "51.52462",
        "longitude": "-0.0720284"
      }
    },
    "offers": {
      "@type": "AggregateOffer",
      "availability": "http://schema.org/InStock",
      "availabilityEnds": "2022-09-14T17:21:42",
      "priceCurrency": "GBP",
      "url": "https://www.outsavvy.com/event/10444/queer-book-club-london",
      "lowPrice": 6,
      "highPrice": 6,
      "availabilityStarts": "2022-11-22T19:59:00",
      "offers": [
        {
          "availability": "http://schema.org/InStock",
          "availabilityEnds": "2022-11-22T19:59:00",
          "name": "General Admission",
          "priceCurrency": "GBP",
          "url": "https://www.outsavvy.com/event/10444/queer-book-club-london",
          "price": 6,
          "availabilityStarts": "2022-09-14T17:21:42",
          "validFrom": "2022-09-14T17:21:42",
          "@type": "Offer"
        }
      ]
    },
    "performer": {
      "@type": "Organization",
      "url": "https://www.outsavvy.com/organiser/sappho-events",
      "description": "Sappho Events produces events for LGBTQ women and non-binary people in the UK. Our events revolve around common interest activities with a coffee and chat vibe. Our social events encourage making new friends and forming connections with other queer people. We also run dating events for queer women and non-binary people, which will be clearly marked.",
      "name": "Sappho Events"
    }
  }
]
```

**Comment by kimadactyl** [comment]
Confirmed working on staging

<img width="1246" alt="Screenshot 2022-10-31 at 11 44 28" src="https://user-images.githubusercontent.com/511734/199000460-d703d647-5f9c-412a-9a3e-42c7cb030b09.png">
<img width="723" alt="Screenshot 2022-10-31 at 11 44 18" src="https://user-images.githubusercontent.com/511734/199000472-75a41a9d-7610-42cf-b8d3-0ca02d7a52cf.png">
