### ISSUE TITLE
Update .env.example with all configurable variables

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1383]
## User story

As a developer setting up the project I need see examples for configurable vars so that I can get my instance set up.

## Acceptance criteria

- [x] If it is possible to override an .env var, that var name is in the .env.example
- [x] If the possible values for the .env var are not obvious, there is an example of a value of the right type
- [x] There are no unused variables in the example

Missed out in https://github.com/geeksforsocialchange/PlaceCal/issues/1351
![image](https://user-images.githubusercontent.com/861172/181270496-20bee956-17b2-459d-8ba9-66f11f256f88.png)

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
This came us because I ususally have to checkout into a special branch to configure which PORT postgres runs on.
@alexandria-gfsc indicated that that has been made configurable by `.env`, but it is not obvious. That prompted me to think that there might be other vars people use on a regular basis that are not listed.

We should make it standard practice to add examples in `.env.example` every time a feature that is configurable by `.env` is implemented.

**Comment by kimadactyl** [comment]
> We should make it standard practice to add examples in `.env.example` every time a feature that is configurable by `.env` is implemented.

That is the idea haha, if it's not happening then oops! Also note that I stickied a comment in the discord to update with our dev settings.

**Comment by kimadactyl** [comment]
All we are now using is google api for geocoding and mapbox for maps right @ivankocienski? Close if you're happy that's the case.
