### ISSUE TITLE
transfer select2 functionality from various behaviors js files into it's own stimulus controller

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1387]
## User story

As a developer adding select2 to my forms I want one place and method of working so that I don't have to worry about which loading events effect which form elements and can limit amount of code I need to read when dealing with bugs.

## Acceptance criteria

- [ ] All Select2 logic is removed from behaviors folder.
- [ ] A Stimulus controller is created that initializes Select2 elements.
- [ ] Clicking the back button no longer breaks Select2 inputs
- [ ] A system test is written to prove that it is working.

## Implementation notes & questions

- I am not sure exactly what will happen when Cocoon inserts extra form elements, hopefully that is specified by the template and should not be an issue.
- Will need to decide how to assign `multiple`.

## Implementation plan

- At this stage I think it is likely that in the HTML `class="select2" will be removed in favor of `data-controller="select2"` which should remove the need for event listeners.
- I imagine that the controller code will be very similar to the internals of the forEach loops that exist to handle this already.

**Comment by kimadactyl** [comment]
Tweaked slightly looks good!

**Comment by aaaaargZombies** [comment]
All but the "collections" page have been done. There are additional form fields rendered in the page that I can't see in the view.

**Comment by aaaaargZombies** [comment]
What amount of test coverage is acceptable / desirable?

- a test that points to a single select2 input on a single page?
- a test for a select2 single and a select2 multiple on a page?
- all inputs that use select2 must be covered by a test?

**Comment by kimadactyl** [comment]
Collections is mothballed for now so all good.

We should prob just cover all select2 inputs yeah - theres not too many and it would be nice for our forms to have better testing in general. The idea of systems tests is to approach the system as an end user and pretend we don't know about the underlying logic so I think the last bullet sounds right.
