### ISSUE TITLE
Refactor test_helper to make it easier to read

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#1404]
## User story

As a developer writing a test, I find it difficult to remember where in test_helper certain functions are, I also find it annoying to discover helper functions by reading the large test_helper file. I would like to be able to find out what helper functions are available to me so I am able to avoid duplicating work that has already been done. I would be able to do do this if the test helpers were split out to be smaller and more module.

## Acceptance criteria

- [ ] There is a new directory, `test/lib`
- [ ] The salient parts of `test_helper.rb` are pulled out into, say, `test/lib/graphql.rb`, or `test/lib/integration.rb`, or `test/lib/{selenium|system|chrome}.rb`, etc.
- [ ] The sets of functions that have been removed and isolated into this new directory, are sectioned off into separate classes and included only inside the modules that they are relevant to / that use them -- see [here](https://guides.rubyonrails.org/testing.html#test-helpers). This is to reduce loading times and reduce the chance of namespace collision.

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
Closing as won't fix. Reference #1919
