### ISSUE TITLE
Write system tests for calendars dashboard

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1405]
## User story

As a developer, I want system tests for the calendars dashboard, in order that if anything breaks I know about it before it hits prod

## Acceptance criteria

There are tests for https://admin.placecal.org/calendars that validates there is...

- [ ] A table with the correct column headings
- [ ] A link to the calendar in the "name" field with the correct title and link destination
- [ ] Text for the partner name
- [ ] Something in notices and errors
- [ ] Last imported looks as it should (e.g. 2 months ago not raw datetime)
- [ ] Last updated looks as it should (e.g. 2 months ago not raw datetime)
- [ ] Clicking "show" and changing the number updates the records shown (note: need to generate lots of records for this)
- [ ] Typing something in "search" correctly filters the list
- [ ] There is a paginator and clicking it changes the page

## Implementation notes & questions

This should soley validate the current functionality so we get notified if it changes

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
A proof of life test for data-tables exist in the select2 tests introduced in #1409 as it is used to navigate to the edit form.
