### ISSUE TITLE
Write system tests for sites dashboard

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#1413]
## User story

As a developer, I want system tests for the sites dashboard, in order that if anything breaks I know about it before it hits prod

## Acceptance criteria

There are tests for https://admin.placecal.org/sites that validates there is...

- [ ] A table with the correct column headings
- [ ] A link to the article in the "name" field with the correct title and link destination
- [ ] Text for the name and the slug
- [ ] Last updated looks as it should (e.g. 2 months ago not raw datetime)
- [ ] Clicking "show" and changing the number updates the records shown (note: need to generate lots of records for this)
- [ ] Typing something in "search" correctly filters the list
- [ ] There is a paginator and clicking it changes the page

## Implementation notes & questions

This should solely validate the current functionality so we get notified if it changes

## Implementation plan

_To be written by the developer_

**Comment by r-ferrier** [comment]
closing as wontfix
