### ISSUE TITLE
Write system tests for neighbourhoods dashboard

### ISSUE THREAD

**Issue by lexiwitch** [geeksforsocialchange/PlaceCal#1414]
## User story

As a developer, I want system tests for the neighbourhoods dashboard, in order that if anything breaks I know about it before it hits prod

## Acceptance criteria

There are tests for https://admin.placecal.org/neighbourhoods that validates there is...

- [ ] A table with the correct column headings
- [ ] A link to the neighbourhood in the "id" field with the correct id and link destination
- [ ] Text for the official key, official value.
- [ ] If the neighbourhood has a `name` and `name_abbr` that these are correctly displayed in the list
- [ ] Clicking "show" and changing the number updates the records shown (note: need to generate lots of records for this)
- [ ] Typing something in "search" correctly filters the list
- [ ] There is a paginator and clicking it changes the page

## Implementation notes & questions

This should solely validate the current functionality so we get notified if it changes.

Note that E99999999 neighbourhoods should be inherently nameless as they are not actual regions, counties, etc. they are just container objects in the ward tree structure.

## Implementation plan

_To be written by the developer_

**Comment by aaaaargZombies** [comment]
A proof of life test for data-tables exist in the select2 tests introduced in #1409 as it is used to navigate to the edit form.

**Comment by r-ferrier** [comment]
closing as wontfix
