### ISSUE TITLE
Rewrite opening times picker in Stimulus

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1417]
## User story

As a developer, I don't want to have one component using Vue, in order that our code base is easier to understand and has less dependancies

## Acceptance criteria

- [x] Opening times picker just uses Stimulus instead
- [ ] Vue removed as dependancy
- [x] Systems tests exist for picker

## Implementation plan

_To be written by the developer_
