### ISSUE TITLE
Delete behaviours folder and tidy up views

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1429]
## User story

As a developer I need remove old code that we no longer use so that other work can continue unimpeded.

## Acceptance criteria

- [ ] Passing tests
- [ ] PR #1424 should already be merged
- [ ] views should not contain `<div class="behavior-trigger" data-behavior="user.form"></div>` etc
- [ ] behaviours js files and related imports removed 

## Implementation notes & questions

This would break select2 inputs on "collections" but this part of the site has been abandoned.

It will resolve the following individual issues: #1419, #1420,  #1422 but will avoid writing more repetitive tickets.

## Implementation plan

- Remove class and data bindings from views
- Remove imports from `admin.js`
- Delete behaviors folder.
