### ISSUE TITLE
Allow people to create events inside PlaceCal

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1437]
## User story

As a partner, I want to be able to make events in PlaceCal natively, in order that I have a simple way to list things even if I don't use other sites.

This is becoming more urgent as every other events platform starts to suck more

## Acceptance criteria

- [ ] Everyone above citizen can create events manually
- [ ] People have access to all the options provided indirectly at present (venue settings, online etc)
- [ ] Events show up in public listings alongside any imported from other sources
- [ ] There is an iCal link people can use to export these events
- [ ] There is a migration route to use a calendar to seed with then disable updates
- [ ] Events created by calendars can be edited in PlaceCal

## Implementation notes & questions

Prob a lot of subtle details to work through here - we deffo need a wireframe

## Implementation plan

_To be written by the developer_

**Comment by erbridge** [comment]
This feels like a fundamentally different proposition than PlaceCal has had so far. I'd rather we pick a provider to be our "don't already have an event listing somewhere? use this thing which works really well with PlaceCal". Let's not reinvent the wheel here when there are plenty of things out there for creating calendars which will be far better at it than PlaceCal ever could.

**Comment by kimadactyl** [comment]
I think the choice is good - our design principle has always been "whatever is easiest for you". I think maybe this is more worth it if we decide to do our own ticketing?

I would also say that reinventing the wheel makes a lot of sense when the only other things out there have rotating rims and underlighting and smoke machines and people just want a new tire :)

**Comment by kimadactyl** [comment]
Possible alternative is we set up an instance of this: https://gath.io/
