### ISSUE TITLE
Automate the first step of boundary migration

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1476]
## User story

As a maintainer of PlaceCal I need to be able to update the regional boundaries when they change so that we can organise PlaceCal to correctly match the geography.

## Acceptance criteria

- [ ] We have a CLI tool we can run to migrate to a new boundary dataset
- [ ] The boundary migration tool generates data migrations for production
- [ ] When a neighbourhood has the same code and parent as the existing data, we swap it in automatically
- [ ] When a neighbourhood has a different code or parent from the existing data is not connected to any other entities, we replace it
- [ ] Otherwise, we generate a TODO in the data migration for human intervention
- [ ] We make sure the data migration is prevented from running until all TODOs are resolved
- [ ] After the migration is run, we don't have any neighbourhoods left over from before the migration
- [ ] After the migration is run, every new neighbourhood is represented in PlaceCal
- [ ] The tool will work for any new dataset with the same data structure (ie we can run it again when the dats changes without writing a new tool)

## Implementation notes & questions

I highly recommend this is delivered in stages, not all in one go.

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Sounds good!

**Comment by katjam** [comment]
Closing as superceeded by neighbourhood permissions work.
