### ISSUE TITLE
Clarify the function of the 'image' field

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1515]
## User story

As a PlaceCal partner, I want to know exactly what to upload in the 'image' field, in order that the website looks consistent and the image is well presented.

## Acceptance criteria

- [ ] 'Image' is retitled to something more precise - i suggest 'photo'
- [ ] Decide if we also want a logo field and if so where that would be used
- [ ] Sweep current content to remove anything that's not a match
- [ ] Update API endpoints and anywhere else this impacts

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
Still valid:

Have a hint on the partner form explaining what size/ratio of image is expected and how it is shown. Also make clear if we want a logo or a photo.
