### ISSUE TITLE
Check and edit the tags of a group of partners at once

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1529]
## User story

As a tag admin, I need to be able to check and edit the tags of a group of partners at once, so that I can quickly and reliably confirm and amend any issues when setting up a new tag.

## Acceptance criteria

- [ ] Tag admins can see which tags partners have assigned
- [ ] Tag admins can filter the list of partners by eg location to see a subset
- [ ] Tag admins can selectively batch edit the tags of a list of partners

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Possibly related to https://github.com/geeksforsocialchange/PlaceCal/issues/1504

**Comment by kimadactyl** [comment]
i think what we have now is good - people are using tags at signup as part of the wizard, and theyre more visible in the admin ui. closing.
