### ISSUE TITLE
Support automatic importing of any ld+json schema.org events

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1536]
## User story

As an organiser, I need to import the events of partners, so that they appear on PlaceCal.

## Acceptance criteria

- [x] If an event listing page with ld+json doesn't fit any of the other criteria for auto-detection, we detect that it contains schema.org events and use a generic ld+json importer.
- [ ] We don't have special instructions or a special importer for Squarespace.
- [ ] We have tests covering all known generators of ld+json event lists.

## Implementation notes & questions

Prompted by #1444 seeming to also use ld+json, but not be a Squarespace site.

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
It would be nice if we can find a tool (browser plugin?) that detects if a page you have has a compatible ld+json feed - be v useful for placecal organisers

**Comment by erbridge** [comment]
We could knock a browser extension together for that very easily, I think.

**Comment by kimadactyl** [comment]
i was thinking of using an existing one but our own one would have lots of benefits to be sure - if it just spots and gives you the correct link that would save a shitload of time for admins im guessing. esp as the vendor list grows it would prob save a lot of time for people.

**Comment by aaaaargZombies** [comment]
started looking into this https://crxjs.dev/vite-plugin

**Comment by erbridge** [comment]
See also: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

However, I think the browser extension is the least important part of this. Let's spawn a new issue for that.

**Comment by erbridge** [comment]
#1546 for the browser extension (later).

**Comment by ivan-kocienski-gfsc** [comment]
So we try fetching a URL and if the response is HTML then we attempt to scan it for ld+json content?

I'm a little concerned that although ld+json is well structured in specific records there's an infinite variety of nesting structures that will have to be dealt with. i.e. we have two importers (Dice and OutSavvy) that are both ld+json but are just different enough to warrant their own extraction logic.

**Comment by erbridge** [comment]
Isn't this what the library we're using is for? To standardise the data structures by "expanding" or "compacting"? If they're being compliant with the standards, we should be able to implement a common parser that works for any standard-compliant implementation.

**Comment by ivan-kocienski-gfsc** [comment]
Do we have a list of known ld-json sources we can use to test the third criteria? It seems like it may be a bit open ended as an AC

**Comment by ivan-kocienski-gfsc** [comment]
I am closing this now as we can find example problem sites as we move forward.
