### ISSUE TITLE
Create a browser extension to detect and surface compatible calendars

### ISSUE THREAD

**Issue by erbridge** [geeksforsocialchange/PlaceCal#1546]
## User story

As an organiser, I need to know what URL to use for a partner's events, so that I can onboard the partner.

## Acceptance criteria

- [ ] I can directly install a browser extension for Chrome, Edge, or Firefox from the admin interface (let's not worry about registering with stores unless we have to)
- [ ] When I'm on a page with a PlaceCal compatible calendar, the extension indicates that fact through an indicator on the icon or similar
- [ ] (optional) When I'm on a page we can predict the location of a PlaceCal compatible calendar from (eg a Google Calendar?), the extension indicates that it has detected that, and skips the manual steps to find the right page
- [ ] The extension shows the correct URL to use for PlaceCal when clicked
- [ ] The extension copies the correct URL into the clipboard on request

## Implementation notes & questions

Building a single cross-browser compatible extension would be best: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
This would be a cool project to think about on it's own feet too. Maybe there's a more generic usecase here - say "computer readable data finder" - that could be it's own funding bid from somewhere or other. It feels like a nice little chunk of the wider PlaceCal mission of having more people publishing more feeds in whatever form suits them, and other people being able to find them.

**Comment by erbridge** [comment]
Possibly, but also, I'm keen to avoid scope creep for something small like this. We can then pull it out and expand it for a broader purpose if we want.

**Comment by kimadactyl** [comment]
Oh yeah I'm assuming this isn't an any time soon thing as it is - more just suggesting that if we name it properly and radiate the intent for the wider project, we might be able to get some developer interest in its own right. 

I guess I'm assuming that this won't be a small thing too as there's not much point doing it without first verifying that this is something the placecal organisers actually _want_ which as you know is a whole slippery slope time wise. I can see it being a bit of a liability too if vendors change their standards and we have to update both placecal and the browser plugin, and at any given point they both have diff versions of the truth. 

Just for a bit of context too, people found installing Faceloader from github very intimidating. It comes up with a lot of scary warning messages if you've never installed non-vendor approved software before, and downloading the exe from github is scary to people. 

It feels big to me as a ticket, but maybe I'm overegging it here. It sounds cool and I want it but it worries me as a distraction (and I know im adding to that lol).

**Comment by erbridge** [comment]
I think this is specifically a tool, embedded in PlaceCal with a button somewhere in the admin interface to click "install the helpful browser extension" (which you can do without going via any stores - or at least you used to be able to the last time I was doing something like this), which then sits in your toolbar being useful. Super low friction from the user's perspective. And because it's a browser extension, we can make it talk to PlaceCal when visiting the admin interface to prompt for updates or whatever. First pass of this is a really quick job, though. We can then see if it's useful and build on it if it is. This ticket describes more than the first pass.
