### ISSUE TITLE
public can filter partners by category

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1644]
## User story

As a citizen looking for groups near me, I want to be able to filter by category so that I can find more relevant listings to do with my specific need

## Acceptance criteria

- [x] `/partners` page allows selecting a category to filter for (all things in that category)
- [x] `/partners` page allows selecting a category to filter out (all things except this category)
- [x] Categories with nothing in don't show up
- [x] make this issue #1774
- [x] Only one category can be selected at a time (radio)
- [x] bonus - hide filters
- [ ] bonus  - clear / all
- [ ] bonus - filter on click

## Implementation notes & questions

This has come up in the PHT groupchat as something holding back the larger listings pages. For example, [Manchester's page](https://manchester.placecal.org/) is getting out of hand now. We have also been sent calendars like a [torbay parents one](https://calendar.google.com/calendar/u/0/embed?src=torbaytots@gmail.com&ctz=Europe/London) that, if every group were added, would swamp the regional listings.

Preview design: https://design.penpot.app/#/view/66c3210d-ba6d-813c-8002-066c130e594f?page-id=66c3210d-ba6d-813c-8002-0651e9d7142b&section=interactions&index=0&share-id=66c3210d-ba6d-813c-8002-0787cb7fe1ed

see ebay / loadstodo as real world examples

This has been flagged as a priority by the team.

This should also close #1668 and #1669 when done.

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
This needs work - self assigning while I triage this
