### ISSUE TITLE
Hide sites with their own frontends from the public

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1649]
## User story

As a member of the public, I want to see the trans dimension proper site not the PlaceCal holding one, in order that I get the best experience for my usecase

## Acceptance criteria

- [ ] Members of the public see https://transdimension.uk/
- [ ] Project admins are still able to see https://trans-dimension.placecal.org/ somehow
- [ ] Robots go to the right place

## Implementation plan

_To be written by the developer_
