### ISSUE TITLE
Partners can self assign themselves to categories and facilities (and not partnerships)

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1653]
## User story

As a PlaceCal user managing a partner, I need to let people know what category of organisation the partner is in order that people can find the partner easily in a crowded listings service.

As a PlaceCal user managing a partner, I need to let people know what facilities the partner has in order that people can find the partner easily in a crowded listings service.

## Acceptance criteria

- [ ] #1766
- [x] I can unassign a service category from any partner I manage
- [x] Partners I manage show up in category results (in the tags page)
- [x] I can assign any number of facilities to any partner I manage
- [x] I can unassign any facilities from any partner I manage
- [x] Partners I manage show up in facility results (in the tags page)
- [x] If I edit a tag to assign it or unassign it to my partner, other partners I am not managing are not removed from this tag

## Implementation plan

- [ ] limit number of category tags to 3
- [x] make tagged partners visible to users with citizen roles in tags tab

**Comment by kimadactyl** [comment]
This may already be done but adding to check
