### ISSUE TITLE
Allow multiple different kinds of "tags"

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1654]
## User story

As a PlaceCal admin, I want to be able to have tags split into different types so they can be used in different ways, in order that we can improve partner metadata and UX

## Acceptance criteria

- [x] "tags" can be of type "facility", "category" or "partnership"
- [x] these are visible in the admin tags index interface both separately and together
- [x] tags are alphebatized
- [x] current tags are assigned the approprate type on prod and staging
- [ ] #1737

## Implementation notes & questions

I think this is a clear case for [Single Table Inheritance](https://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html).

## Implementation plan

- [x] put type field on Tags table
- [x] #1687
- [x] #1690
- [x] #1692
- [x] #1695
- [x] #1702
- [x] #1708
- [ ] update controller/model/policy/tests to allow tag selection (as needed)

(guest user front end work will be done after this issue is closed)

**Comment by ivan-kocienski-gfsc** [comment]
I have had a pass at this and so far I have identified 3 kinds of tags on PlaceCal:
- *Property Tags* - on Partners to indicate they have a particular service or feature. i.e. Accessible Toilette, Free Wifi, Public Computers
- *Category Tags* - on Partners and Events to indicate the (primary) subject of the event. i.e. cooking, biking, music
- *Site Tags* - that link Partners to specific Sites, like Trans Dimension

**Comment by kimadactyl** [comment]
I like these but just vote to rename "properties" as "facilities"? i think the former is a bit programming-y?

**Comment by kimadactyl** [comment]
The last step here is huge scope creep and covered by other tickets

**Comment by ivan-kocienski-gfsc** [comment]
Could I get an expansion on what you meant by "these are visible in the admin interface both separately and together"?

Do you mean: Users can select all types of tags from the one tags box?
Or do you mean: There will be three separate (tag) boxes: Categories, Facilities and Partnerships?

**Comment by kimadactyl** [comment]
I meant that

- You can see the list of all tags
- you can also see the list of just categories
- you can also see the list of just facilities
- you can also see the list of just partnerships

i think eventually we want to discontinue the first one entirely - but for now at least make it so we can browse each category individually?

its really seeming like replacing datatables is becoming a big blocker huh

**Comment by kimadactyl** [comment]
possible inspiration: https://github.com/geeksforsocialchange/gofg-db/blob/master/app/views/people/index.html.erb

**Comment by katjam** [comment]
> The last step here is huge scope creep and covered by other tickets

I agree we ditch the "as needed" & "more to come" part & maybe update to "Update relevant tests to cover new tag model & any changes to policies"

**Comment by katjam** [comment]
> I meant that
> 
> * You can see the list of all tags
> * you can also see the list of just categories
> * you can also see the list of just facilities
> * you can also see the list of just partnerships
> 

I am assuming that "you can see" means "admin can see & select from"

**Comment by kimadactyl** [comment]
Yes to both - to me this entire ticket is just about getting the new concepts in the backend and having a proper think about them
