### ISSUE TITLE
Show baby and toddler groups

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1668]
## User story

As a parent, I want to be able to just see baby and toddler groups, in order that I can quickly find relevant groups for me

## Acceptance criteria

- [ ] I can select a partner filter that just shows baby and toddler
- [ ] Organisers can tag groups baby and toddler
- [ ] Decide if this is the right tag or if we want to rename this for example, age category

## Implementation notes & questions

Consider #1655 first

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
Closing as will be fixed  by #1644
