### ISSUE TITLE
Add a tag for partnerships

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1671]
## User story

As someone running a partnership, I want to have a special tag for my group of partners that only I control, in order that I can create a page for membership of my group

## Acceptance criteria

- [ ] Organisers can have tags only they can apply or remove
- [ ] These tags are not shown in public filter interface
- [ ] Tags are shown on partner pages as memberships

## Implementation plan

_To be written by the developer_
