### ISSUE TITLE
Remove "edit permission" picker from Tags 

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1708]
## Description

This functionality should now be provided by the tag type and not a separate field

Partnership tags should have the current functionality of "Root: Non-Root users must explicitly be granted permission to assign this tag"

Category and facility tags should have the functionality of "All: Any user may assign this tag"

Works towards completing these 3 parts of the Tag spec:

- Up to 3 Category Tags can be assigned to Partners by anyone who can edit that Partner *(currently controlled with `edit permission: all`)*
- Any number of Facilities Tags can be assigned to Partners by anyone who can edit that Partner *(currently controlled with `edit permission: all`)*
- Partnership Tags can be assigned to Partners by only roots and Partnership Tag Admins *(currently controlled with `edit permission: root`)*

## Acceptance criteria

- [ ] edit permission field is removed from interface
- [ ] edit permission field is dropped from database
- [ ] ~~field type sets the permission instead~~
- [ ] ~~"assigned users" only shows up if it's a partnership tag~~

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
I would keep this ticket as just about removing the interface (and maybe db field).

I would suggest the security/validity of tags should be looked at as a whole. Like- for each kind of tag what can/can't be done and by whom and so on.

**Comment by kimadactyl** [comment]
yep - agree. no intent here to add or remove any policies, its just db/ui tidyup

**Comment by kimadactyl** [comment]
Memoing that following a chat with Ivan we realised this was about making every tag useable by everyone for now and revisiting permissions at a later date
