### ISSUE TITLE
Lock down Partnership Tags

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1713]
## User story

As a PlaceCal admin, I only want to be able to see my partnership tags and noone elses, in order that my interface doens't get hugely cluttered and we don't accidentally edit each other's stuff

## Acceptance criteria

- [x] Roots can see every Tag
- [x] Partnership admins can see their own Partnership Tag(s), plus all Categories and Facilities in all relevant dropdown menus
- [x] Everyone else can only see all Categories and Facilities in all relevant dropdown menus
- [x] Create another ticket for enforcing this in the backend - for now this can be a frontend-only change.

## Implementation plan

_initial plan_

- look into where tags can be accessed in the admin UI
- look to filter them depending on user
- add system tests to verify
