### ISSUE TITLE
Allow guests to filter partner listings by ward

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1733]
## User story

As someone browsing manchester.placecal.org, I want to be able to limit my results to just one ward, in order that I can find things just in my area

## Acceptance criteria

- [ ] manchester.placecal.org/partners has a list of wards i can filter to ([inspiration](https://loadstodo.co.uk/whats-on/))
- [ ] clicking a ward shows just partners in that ward
- [ ] clicking a diff ward changes from one to the other (not both)
- [ ] i can clear the ward selection
- [ ] Let people know this can now begin: https://github.com/geeksforsocialchange/PlaceCal/issues/1828

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
A bit naughty to add to this milestone but hopefully this is the same frontend code as #1644

**Comment by kimadactyl** [comment]
Bumping this into current milestone so as to not lose track of this ticket which is really important!

I think this is a real blocker as we can't start pushing the regional sites till it's done.

Probably events filters needs doing too tho - so maybe its a new milestone

**Comment by katjam** [comment]
Moving to Dream Yard because although the filter need may come up when we have more content, we'd like to base it's development on need arising from use, rather than assuming ward is the most natural.

**Comment by kimadactyl** [comment]
IMO that's incredibly well established at this point for multiple audiences across multiple formats - without it the partner listings on the Manchester site are pretty unusable.

**Comment by kimadactyl** [comment]
Bumping this into an active milestone following chat with @katjam - being able to filter down entries somehow on the partners page feels really urgent as manchester is a bit unusable atm and this is by far the simplest extra thing we could do that also answers a lot of pertinent user stories.

**Comment by aaaaargZombies** [comment]
## verified

- manchester.placecal.org/partners has a list of neighbourhoods I can filter to

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/121d99ec-8197-4b8b-9be5-5986b6bbe170)

- clicking a name shows just partners that have that name badge

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/2f2ca29e-8920-4996-9cb3-5a3bb478f63d)

- clicking a diff neighbourhood changes from one to the other (not both)

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/3d28bc9a-b55a-486d-b78c-844bf102942a)

- I can clear the neighbourhood selection

https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/53297c57-2b36-41af-8cd3-ac6eb9aa8a0e

- Let people know this can now begin: https://github.com/geeksforsocialchange/PlaceCal/issues/1828

Not sure who we let know, maybe dev team, I'll pop a message in discord.
