### ISSUE TITLE
Remove all restrictions from scopes that apply to root users

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1765]
## User story

As a root user I need to be able to access everything.

## Acceptance criteria

- [ ] Any root user can view all sites in admin
- [ ] Any root user can view all tags in admin
- [ ] No other user role can view all tags or sites in admin

## Implementation notes & questions

This issue exists because of a quick fix that was made at some point to give some users root access to enable them to admin their own sites and tags, due to issues with permissions. Once these issues with permissions have been fixed, their status as root users should be revoked and all permissions should be restored to all remaining root users, which at this point should just be technical staff/ product owners.

This should be able to be addressed by reverting PRs associated with issues #1763 and #1746.

We need to check that there are no other areas with restricted root access and add these to the above acceptance criteria.

## Implementation plan

_To be written by the developer_
