### ISSUE TITLE
Add Norwich neighbourhood calendar

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#1800]
## User story

As a person living in Norwich I need to be able to see events in Norwich easily so that I can connect with my community.

## Acceptance criteria

- [x] norwich.placecal.org exists! 
- [x] norwich.placecal.org is not public site
- [x] norwich has logo set
- [x] @honor-gfsc  is site admin
- [x] @honor-gfsc is neighbourhood admin for norwich
- [x] ~@honor-gfsc knows how to add partners to the site~ - removed from scope
- [ ] There is at least one partner with a calendar of events in the site (as a test to see everything working and honor being able to explain to people what it does / is for)
- [x] There is some branding - (@undividual maybe help with logo?)
- [x] The [handbook](https://gfsc.notion.site/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc) on how to make a new site is accurate (make edits if not clear)

## Implementation notes & questions

- Create Site record on PC
- Amend DNS (needed?)
- Add SSL cert

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
This is a good opportunity for us to write down what needs to happen to make a new site i think. 

Step 1 is talking to @undividual about making a placecal norwich logo, picking one of the four colour schemes, sourcing an image for it from creative commons, then theres a tiny bit of dev team work to do. im sure theres a notion page for this somewhere thats been started!

**Comment by undividual** [comment]
Just to note that I am on standby for this — please just @ me to confirm colour scheme and I'll get the logos made, or slide in my DMs if you wanna discuss the colour schemes or anything else.

**Comment by ivan-kocienski-gfsc** [comment]
This requires some DNS/SSL wrangling? I created a [norwich.placecal-staging.org](https://norwich.placecal-staging.org) site but I it is not accessible.

**Comment by kimadactyl** [comment]
Handbook page is https://www.notion.so/gfsc/Creating-a-new-PlaceCal-Site-bd90494c88e74bfe94c306f714ede8dc?pvs=4

**Comment by honor-gfsc** [comment]
@undividual can we have an orange logo for this please

**Comment by undividual** [comment]
PNGs below. Welcome to PlaceCal! 🤩
![PlaceCalNorwich_Darkbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/58667337-9969-43ca-86b3-19bf32c1b766)
![PlaceCalNorwich_Lightbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/434b37c9-785c-4d20-b06c-c86672fc756a)

**Comment by ivan-kocienski-gfsc** [comment]
I have set up Norwich on staging https://norwich.placecal-staging.org and given @honor-gfsc ownership and added a logo.

Have set up https://norwich.staging.org and given it the logo. Honor does not have a log in on production (or i am missing it) so it is just me.

**Comment by ivan-kocienski-gfsc** [comment]
@katjam i was keeping people (kim and honor) updated on the discord and told them about doing it on staging first as a dry run (call me paranoid but i don't like doing things directly on production without any safety net or supervision). It has been done on production as well.

**Comment by ivan-kocienski-gfsc** [comment]
I have expanded on the handbook spelling out the steps more clearly (i hope).

**Comment by katjam** [comment]
> @katjam i was keeping people (kim and honor) updated on the discord and told them about doing it on staging first as a dry run (call me paranoid but i don't like doing things directly on production without any safety net or supervision). It has been done on production as well.

Sounds very sensible. I guess we can remove the test instance and update this issue to reflect.

**Comment by honor-gfsc** [comment]
@undividual can you please email me the logo files as when i downloaded from here they aren't transparent

**Comment by undividual** [comment]
![PlaceCalNorwich_Darkbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/dd8772a1-2ff9-471b-8fdd-b0e2e262ab5d)
![PlaceCalNorwich_Lightbg](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/d2dbf214-34ec-4932-b601-eb58c8605f98)

SVGs above!
