### ISSUE TITLE
When I visit a sub-site linked from placecal.org it is not obvious how to get back

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1804]
## User story

As a person discovering a PlaceCal site by exploring from the root site, I need to be able to get back to the root site easily so that I don't feel lost or stranded.

## Acceptance criteria (TBC - none of these is perfect)

- [ ] When I reach a sub-site from the main site, I can see how to easily get back
- [ ] There is an obvious way to get to the PlaceCal root site from every sub-site
- [ ] As suib-site linked form the root site always opens in a new tab or window?

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
Raised by PHT steering group
