### ISSUE TITLE
Allow updating neighbourhoods to the latest version

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1809]
Get the data about UK boundaries from the government website into PlaceCal

## Acceptance criteria

- [ ] I can upload data from the government database into PlaceCal
- [ ] What happens to existing wards?
- [ ] What happens to new wards?
- [ ] Add more acceptance criteria

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
This was covered in PR #2002
