### ISSUE TITLE
Clear out existing "about PlaceCal" home

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1810]
We want to start with an empty shell.

## Acceptance criteria

- [x] The site home consists of just header and footer
- [ ] Include if it seems easy, if not, shard to it's own issue: The site wrapper / shared across pages (e.g. header, footer) content uses new design system
- [x] The metadata is accurate & present
- [x] Retain header menu as it is 
- [ ] #1823

## Implementation notes & questions
We probably need to be a little more specific about what stays, like do we definitely want to have footer? Not sure if Mark's new design stuff is components only or if there are also layouts.

In terms of the header navigation, we decided to keep it - Kim uses the "Our Story" page a lot. It might not need to be in the navigation after this refresh, but we need the content to be accessible from somewhere.

## Implementation plan

- [ ] 

_To be written by the developer_

**Comment by kimadactyl** [comment]
Just to note I would like to keep these pages as they are helpful, but the links can live in the footer for now?

**Comment by kimadactyl** [comment]
I also don't know if we need to change this all at once - imo we could do more iteratively? Like we can develop the new pages before putting them in the main navigation, even

**Comment by katjam** [comment]
For ref. https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/ https://www.dropbox.com/sh/v4ifllv0tki83tu/AAClxFi1k6NJ4FAWXNwuoAdBa?dl=0

**Comment by kimadactyl** [comment]
The only thing to be aware of when redoing the navigation is i think it's at breaking point right now and if it goes any wider it needs a rethink - check responsive sizes when working on this

**Comment by studiosquid** [comment]
**Layouts** 
There's no layouts in what I supplied but it's no problem to quickly rough them out as that's how I essentially created the components.

**Footers**
There are a few components / roughs of footers which are hopefully a bit more flexible than the original 2020 and 2017 versions. 

**Navigation** 
I was very unclear whether the navigation would change when producing the design system, so I have left that alone in what I've produced so far, though at one of the smaller states I do show what happens if the navigation suddenly ends up with lots of extra links. 

In terms of clarity of message I'd hope we'd want a very streamlined main navigation really, with the more detailed old pages potentially hidden within broader stroke pages like About.

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/235626606-13532f3a-5a4a-4073-bc56-265767ba6441.png)

**Comment by katjam** [comment]
![image](https://user-images.githubusercontent.com/861172/235646216-8ee21ede-03ee-45ae-98eb-87007a5c3ccf.png)

**Comment by katjam** [comment]
@studiosquid will redesign the footer. Maybe retain main nav?

**Comment by katjam** [comment]
Not verified independently. This was an initial stop that got superseded.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/58b758c1-b48b-4914-a221-cc1fdff51cac)
