### ISSUE TITLE
Implement refreshed PlaceCal design system

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1812]
XD walk through of everything:
https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/

Dropbox folder containing assets:
https://www.dropbox.com/sh/v4ifllv0tki83tu/AAClxFi1k6NJ4FAWXNwuoAdBa?dl=0
Contains a few new SVGs, the master XD file, and PNG backings of XD file.

## Acceptance criteria

- [x] #1988
- [x] Site home page text is pushed into user control (#1699)
- [ ] Existing sites have descriptions either migrated from what it is now or added manually (maybe a good chance to cull dead sites)
- [ ] #1943
- [ ] [Update with breakdown of components to implement]

## Implementation plan

- #3000 
- #3010 
- Attempt automigrate of Sass -> Tailwind

**Comment by katjam** [comment]
This may or may not be a thing we want to do - to keep consistency between new homepage / info site & the sub-sites

**Comment by studiosquid** [comment]
Designing in consistency of the sub-sites was something that was originally requested (but I realise PlaceCal is pretty fluid) reason was those are all working on the very original 2017 designs and I believe we've run into quite a lot of issues since they first began. 

But also there feels like quite a lot of push for either more generic or more customisable versions. (Or both!)

I did do a draft where I took out all the PlaceCal colours and took it a more neutral place except for an accent colour. I parked this for now as it tended to look very cold and unwelcoming, and the accent colour would have to be either manually checked, or picked from a preset list of colours so that accessibility isn't scrambled.

**Comment by katjam** [comment]
Removing from priorities - but is a good idea & has designs

**Comment by r-ferrier** [comment]
I've also added another item to the acceptance criteria on #1699 related to this

**Comment by kimadactyl** [comment]
just have a read of the other ones. doesnt have to be fancy - just a record of the problem definition and what options you considered. if you open a pr with just that then we can discuss before geetting stuck in :)
