### ISSUE TITLE
Implement footer with agreed content

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1823]
## Acceptance criteria

- [x] only the GFSC logo links out from the placecal website
- [x] privacy policy looks like a link not part of the address
- [x] upper links are reduced down to the following as per screenshot
    - email
    - admin login
    - join
- [x] footer should take inspiration from Marks [wireframes](https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/60498a69-b830-493f-b479-476c90ebfb13/specs/) but does not need to implement exactly
- [x] update copyright date
- [x] add lankelly chase logo to sponsors 

## Implementation notes & questions 

![footer notes](https://user-images.githubusercontent.com/861172/235646216-8ee21ede-03ee-45ae-98eb-87007a5c3ccf.png)

@studiosquid will redesign the footer. Maybe retain main nav?

split off from #1810

## Implementation plan

- there is no specific design for the current content I will use [Footer A](https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/screen/60498a69-b830-493f-b479-476c90ebfb13/specs/) as reference, replacing the repeated main nav with the upper links.
- I expect there to be a first draft followed by feedback in PR on visuals
- I will not implement the site navigation in the footer

**Comment by aaaaargZombies** [comment]
footer A desktop

![](https://uc81e371d6462d19b4625f94ded3.previews.dropboxusercontent.com/p/thumb/AB5E78SBoEhv_lp0MZ-XEY_QMtjJ_QPFXT8wTkOyj_-tJYcx_AdF70Kgu_Y8S5B4cx4I3ZNa6XkUX0yKKeGCo2tBuATfiBCWH7K9q6_DYbWK3231tEf14AWPg4B3IKZQf1b-cPIjqOW3FrA_-Fsdu1PyE-IElumTF1iTcJ_UGJfvdGhk08vwaNn4VGi1esyPzME0Dp10woA3oKjkeFHh7p9zPSMqS_7M3e_RXbt34TS2mUeE5wdingZuxzTnaJSs4Tzd7fyWAKEGYFYUL4iZvLJhUaJEWvOKEX_sc2hpwf8m5iVtgyH-Pgn1Bg5LqWiomHiotPquac1WSKninh1CJot1kWJBENxhEela-Sv_SgzD5b8US6Pvn5Cs14Xsc9pSMja-UGbhZPS-8fJUSRdKwNBXmSIvvYlfQCmN3rEkVU8bmw/p.png)

footer A mobile

![](https://uce281b091797c14c9eded47e2d6.previews.dropboxusercontent.com/p/thumb/AB4Mfu2Yw-fyxUllRCq3HmKsrrSXJcnAeNmXSS3YPfRPbn7Uu5mEbNigYvGc9j0rniydTG5up9qmgdpu3yT_EieWCGbCTnh4vBgvZIdfYnZE8iykxF9xnQKSDXG2lO8KHnBMscYtkcLsCuIu-TBn3R6eJefSdKeT6oAOnassN27wx7jyUm2PisnxXHwW-CFj6WMNh-HT0q269hpJ0Zkc2lODNMZIueoWXbmWLVUruMQ4qdnvFa3O9aDV8zrOWEnlAjJMzGi6XfUCnp3Mk7VrxPDRRPJKvWnNgV9GpfnUWzK0Vn8TB8gP5C3Rrut0xkuOhvGBeRYA8XbSTnMmKtQRvwCEQV19osAoYH3ofA8zUKI9olpl2JzT5R33TCeDt3-3hhZx1fsOjW9lz4rrezwuslKgOgbh9yEqIbhv8KmJPzLcsQ/p.png)

**Comment by studiosquid** [comment]
This is looking great to me — there's only one issue which is the lack of login link — could this sit alongside the Privacy Policy or is that too buried? (Or is that an instance / sub-site only issue?)

**Comment by studiosquid** [comment]
That sounds good to me.

**Comment by kimadactyl** [comment]
I think we should prob add lankelly chase as sponsor too if thats ok? would you be ok to make a version of the logo suitable to go there @studiosquid? https://lankellychase.org.uk/

**Comment by studiosquid** [comment]
@kimadactyl fingers crossed, couldn't extract an SVG has some odd shading. 

![LankellyChase](https://user-images.githubusercontent.com/9461465/235965204-46416758-84d5-4fa3-b864-3379c3dc5247.png)
