### ISSUE TITLE
The homepage contains a very concise description of what PlaceCal is (tag line)

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1829]
## Acceptance criteria

- [ ] There is a feature area on the homepage with concise text (use text from site for now)
> PlaceCal is a community directory and events calendar where you can find out everything that’s happening in your neighbourhood all in one place.
- [ ] Replace temp copy in "concise description" box on the homepage
- [ ] The component is implemented as a view component
- [ ] The design matches the image below (without button?)

## implementation plan

- no white title as it's extra words and doesn't meet acceptable contrast threshold
- no button as we have a link in the nav
- use this design
- checkout commit 1abc4fe7 if you would like to see how the original version was implemented

![Screenshot 2023-05-04 at 14-54-43 The homepage contains a very concise description of what PlaceCal is (tag line) · Issue #1829 · geeksforsocialchange_PlaceCal](https://user-images.githubusercontent.com/6824891/236230235-2691d6d3-e3c0-4b9b-8c67-fbf0705f4d15.png)

**Comment by katjam** [comment]
This will be useful for copy: https://www.notion.so/gfsc/PlaceCal-Pitching-Slide-Deck-177301f1c64c4658beb395079759612a?pvs=4

**Comment by studiosquid** [comment]
This is where the components having actual names would come in handily! But the page which the most relevant components as a starting point are titled Generic boxes and info elements in the XD preview. 

I haven't included a design for what an image one would look like but basically any of the cream ones with text, drop the text and with an image in them with comfortable spacing. 

![1_Web 1366 – Generic boxes and info elements](https://user-images.githubusercontent.com/9461465/236184000-f275ac99-0394-4b6d-959c-e1eb65be009d.png)

**Comment by studiosquid** [comment]
For the intro box I'd suggest we just reuse the old one until we have that content produced, it's a nice short length of text includes the illustrations. I've done some very crude versions and attached a mock, you could just use some of the simpler components for now. 

There's a chicken / egg with the text we need. PlaceCal is difficult to summarise so I don't think it's be great to dictate a word count here. (Short ideal of course.)


![Homepage-header-mock](https://user-images.githubusercontent.com/9461465/236185860-49c1d07a-f4b3-4bf6-b5b8-6b7bbc7cbd5f.png)
