### ISSUE TITLE
"what can I do here" content to be signed off

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1843]
It currently looks like this 

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/d02f25df-a5b2-4839-9e72-2bf76898f739)

## acceptance criteria

- [x] Find your PlaceCal - Ready to get started with PlaceCal? Here you can see a list of all current PlaceCal instances, organised by interest and location.  - See calendars 
- [x] Want to create a PlaceCal for your community?  - Work with us to set up a PlaceCal for your community, built through on-the-ground connections with venues, organisers, and community members. - Get in touch 
- [x] How did PlaceCal start? - We wanted to examine the causes of social isolation and loneliness within communities in order to figure out how to combat them.  - [Learn more](/our-story)

## implementation plan

"actions" need the following details

-  title, 
- link_text,
- link_url,
- color: 'blue' | 'cream' | 'green' | 'red'

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/dd508dbf-9b22-4634-9439-eb69bcaf5a97)

**Comment by r-ferrier** [comment]
verified in #1869
