### ISSUE TITLE
create a component for place based instances

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1844]
## acceptance criteria

- [ ] requires individual "card" components
- [ ] larger "find your neighborhood" component should accept any number of cards as children
- [ ] used on `/find-placecal` with all neighborhoods
- [ ] used on `/` with 4 selected neighborhoods

## implementation plan

The bottom part of this mock up "check out a neighborhood"

Don't include the lorem filled text as discussed in meeting

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/852511ff-f911-4630-8971-62b717cd24fa)

see #1818 for list of homepage neighborhoods
