### ISSUE TITLE
create a component for partnership instances

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#1845]
## acceptance criteria

- [ ] [cCc] make a component, maybe nested ones
- [ ] appears on Find PlaceCal page (`/find-placecal`)
- [ ] Each card has a short description (from the Site Tagline field)
- [ ] link text

## Prerequisites
- [ ] wireframe of component
    [here](https://user-images.githubusercontent.com/9461465/236183310-a6c13ad2-4657-4d18-b8e6-4ceccc5abd63.png)
- [ ] colors/fonts 
    (probably in the CSS already, also check live production)
- [ ] mockup graphic
    (see below)
- [ ] UX considerations (links to other pages, hover/click states)
    The links point to the live production sites (like trans-dimension.org)

## implementation plan

The top row of items "visit a partnership"

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/b10d896c-db4d-4368-8c30-b0531aec2581)

**Comment by kimadactyl** [comment]
I think we were going with the bottom row thing not the top one!

this also shows up on the new homepage i think

just a small note on the prereqs that we only need a design or a wireframe - not both. ideally former, latter also fine but the latter is a step to the former.

i think the criteria should be clearer too - one criteria per component. so if the grid is one and the individual item is one and the title is one, that 3 components for ex. We can then use this to more clearly signal where we are going to do some reuse

**Comment by kimadactyl** [comment]
ah - also confused as this ticket talks about both partners and partnerships and the screenshot has neighbourhoods in it - which is it?

**Comment by kimadactyl** [comment]
one last final issue - the screenshot and wireframe links are different.

**Comment by ivan-kocienski-gfsc** [comment]
Progress:

![Screenshot_20230511_150056](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/fa2f3152-4d84-4760-aee3-18386ca53515)

- logo comes from view
- link url comes from view
- summary comes from view

**Comment by ivan-kocienski-gfsc** [comment]
More progress:

![Screenshot_20230511_164702](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/184c765b-dbe5-41df-b3db-52582edf0301)

**Comment by r-ferrier** [comment]
Final implementation:

![Screenshot 2023-05-22 at 12 55 19](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/63887a6c-8b9b-4b9e-8dc9-d11d85872d0a)

![Screenshot 2023-05-22 at 12 55 10](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/bfcf477e-4b76-4479-a26f-70e6c1b388aa)

![Screenshot 2023-05-22 at 12 55 26](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/acc38abd-4035-4d27-8adc-acde399377d3)
