### ISSUE TITLE
Content for Find Your Placecal

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/PlaceCal#1857]
## Issue

Content is approved for featured partnerships & neighbourhood instances

![Screenshot 2023-05-11 at 18 52 51](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/8e24a278-83de-4203-97eb-c8b9c613d55e)

![Screenshot 2023-05-11 at 18 52 37](https://github.com/geeksforsocialchange/PlaceCal/assets/46496391/366edc84-08a0-4feb-9a4a-3e6a46429b35)

- [ ] All featured neighbourhoods are correct & have correct links & destinations
- [ ] All featured partnerships are correct & have correct links & destinations
- [ ] All featured partnerships have approved summary

## Acceptance criteria
- [x] Links go to event page, not home page - text is "[name of place] calendar"
- [x] On neighbourhoods - title is [Neighbourhood name] and button is [Name of place] calendar, overall title is "Place-based calendars"
- [x] On partnerships - overall title is "Interest-based Calendars"
- [x] page title - "Here's a list of all PlaceCal instances, organised by interest and location. "
- [x] CTA - Set up PlaceCal in your community - Get in touch 

## Implementation Plan

- Featured neighborhoods are selected by "publishing" a site int he admin UI. This won't happen on release and will need doing on the production site.

**Comment by r-ferrier** [comment]
verified by #1869
