### ISSUE TITLE
Improvements to partner filtering

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#1906]
## User story

Whe I filter a list of partners by a category that has none, it should be obvious to me that I have landed on an empty list & what I have filtered by,

## Acceptance criteria (TBC)

- [x] If there are no results from a partner filter, there is some text indicating no partners found
- [x] #1909
- [x] When I submit a filter option, I can see that filter in my screen (dropdown remains open? or some breadcrumb like text appears at top of results)
- [x] I can reset the selected filters regardless of whether I have submitted (see verify notes on #1778)
- [x] It is clear that I can filter when I land on the page "Category" maybe change to "Filter by Category"
- [x] The text on the radio controls should be clickable also, the radio button itself is a tiny target

## Implementation notes & questions
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/be9d59c9-9e92-4df1-a08d-1dfa10780887)

## Implementation plan

_To be written by the developer_

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ac060d52-b124-4a94-8e36-2ae809423a22)

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ca131466-5e83-4ace-92e2-4c17256f8a3a)
