### ISSUE TITLE
[Epic] Allow a wide range of logos to be uploaded

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#1943]
## User story

Currently we have very specific requirements for logo uploads. We should allow a range of formats and sizes.

## Acceptance criteria

- [ ] #1966
- [x] #1981
- [ ] Logos with both transparent and coloured backgrounds look ok
- [ ] #1982
- [x] Bonus: nicer image uploader widget poss using Stimulus?
  - [ ] with an image editor
    - https://github.com/fishpercolator/name.pn/blob/main/app/javascript/controllers/likeness_uploader_controller.js
    - https://uppy.io/docs/image-editor/

## Implementation notes & questions

for bonus see

## Implementation plan

_To be written by the developer_

**Comment by undividual** [comment]
This is in reference to our chat just now on discord, right? As luck would have it, Mark has just sent me some XD files for unrelated work on colour schemes, so I will put some thought to this.

**Comment by undividual** [comment]
So I wanted to respond to this as me and Mark have been chatting about this, and we have a couple of suggestions depending on the planned approach to these pages overall.

Approach 1)
If we are keen to fix this issue but entirely stick to the existing design, Mark suggests a simply switch of the light beige areas of the site to white, as per the screenshot below. (So, the area where the logo and nav currently sit, and the area directly below the image, plus any other similarly shaded areas further down.

![Screenshot 2023-08-07 at 11 42 18](https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/8ed4932b-81c3-4275-99d2-06302feada76)

Approach 2)
If we have capacity to undertake a much wider refresh of these pages, Mark has been working on some revised designs, screenshot below... However I appreciate this goes well beyond the scope of this ticket. 
<img width="1921" alt="Screenshot 2023-07-31 at 10 07 04" src="https://github.com/geeksforsocialchange/PlaceCal/assets/90701712/ad79c9ce-6b2d-427f-98a4-93f388bda04b">

Approach 3)
From Mark: "I do wonder if there's a halfway house we could propose, which is to update the underlying structure/grid so that things are the same widths as the new main site — the narrowness of the 2017 design is what caused a lot of issues with random things like lengths of emails etc. But not a dev so I don't know if that itself is a total nightmare and not worth approaching." — so basically, the design styling of approach 1, but with some additional work on the overall widths of the site), again, beyond the scope of this ticket I know.

I am leaving these here to be pondered, please feel free to summon me if you need any more guidance, whichever approach you take!

**Comment by kimadactyl** [comment]
@undividual just to note that approach 2 is the intended route, this ticket is a step as part of this one https://github.com/geeksforsocialchange/PlaceCal/issues/1812 (and noting too this is why i think we should always be working from design masters)

**Comment by undividual** [comment]
100% — just noting the spectrum of options here, and if route 2 is the route to go down, Mark has supplied XD files to this effect (albeit only at one size so far). However I wasn't sure how urgent this issue is, and if the answer is 'very', route 1 offers a quick fix.

**Comment by kimadactyl** [comment]
Ahh I see is this design different to the current provided design? I didn't check :)

**Comment by undividual** [comment]
Yes, I think this is new work that is still in progress, to re-envision the instance pages. (This also affects my work to develop new colour schemes, as I should probably do them based on these new designs once they are implemented). Prob need to have a bigger conversation about plans to implement these at some point. (Also forgive my ignorance, I haven't done much on PlaceCal thus far so I am coming new to these files and where things are at!)

**Comment by kimadactyl** [comment]
OK now I'm more confused!

There is an XD file in the linked ticket https://github.com/geeksforsocialchange/PlaceCal/issues/1812 that is the eventual end goal to aim for: https://xd.adobe.com/view/d737e480-ff3a-4e07-8d32-339f902ddf4b-8264/grid

Are you saying the screenshot given above is different to this XD file?

**Comment by undividual** [comment]
Yes and no — the XD file above is the current source of truth. Mark did a little sample version screenshotted above showing a) a sample jazzier colour scheme and b) a solution to the 'logos need white backgrounds' issue. 

Assuming the 'quick fix' of approach 1 is not required, we should work to implement designs according to the XD file you've linked. That said, that XD file does not contain a fix to the issue being discussed in this ticket (i.e. white backgrounds) but it would be very easy to implement that once that version is built.

I hope that makes sense. It seems like this issue should pause for now until the new designs for instance pages are implemented.
