### ISSUE TITLE
show future events on site index

### ISSUE THREAD

**Issue by honor-gfsc** [geeksforsocialchange/PlaceCal#1987]
## User story

As a site admin I need to be able to set the default view to be weekly so that the site appears busy and in-use even with relatively few partners.

## Acceptance criteria

- [ ] a site with future events always shows events on first load of the events index
- [ ] default to showing all future events
- [ ] fall back to day as the default if future events is `>200`
- [ ] if showing future events hide the date pills
- [ ] add "show all" option to filter menu

## Implementation notes & questions

Possible fixes from honor

- the default view for events is configurable to be weekly or monthly by the site admin and doesn't reset to daily every time the listings page is visited
- alternatively, it shows something smart depending on event count? (e.g. weekly view if theres less than 10 events a week, monthly if less than 20 events a month, etc). poss too fiddly to work out an algo?

The later option sounds most useful but we need to investigate alternative forms of pagination, https://transdimension.uk/events `future events` option seems like a sensible but would require some re-working of the UI

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/f22dacae-4fb5-4b54-ac4a-b1948418022a)

Probably add `future` after `weekly` and dropping the pagination at the top ?

Set `day | week | future` based on min `n` events in controller.

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
A more ambitious version of this is here: #832

**Comment by kimadactyl** [comment]
Do you think this is an onboarding UX issue @honor-gfsc?

**Comment by honor-gfsc** [comment]
I think it's an issue which impacts how PlaceCal *looks* to potential users – PlaceCal Norwich right now looks pretty much empty and unused on first glance even though we have approx 10 events a month listed, just because of the default view. Would be a big quality of life improvement, imo. I would want this to be configurable both for a partner and for a site as a whole, by the site admin.

**Comment by kimadactyl** [comment]
This issue is affecting https://climatejustice.placecal.org/ too - they have events added but you can't see them. I think I agree with honor, this is pretty critical actually for the experience of new organisers.

**Comment by aaaaargZombies** [comment]
I did a very basic implementation, trying to achieve a minimum of 10 events on first visit to the index page.

https://github.com/geeksforsocialchange/PlaceCal/blob/3d2336661ce5fbd66a43ae5d663333931c9a70ee/app/controllers/events_controller.rb#L19-L38

currently it is `day | week | future`

Much of the complexity that remains relates to the pagination controls.

We could potentially just increment the date until we hit the first day with an event but I think as soon as someone moves off that day we will be in the same boat. Although I think it's not the best option I'd still like to hear others thoughts so it's not discounted by accident. 

## questions

- What should the larger unit be, we could go month, paginate per `x` events or show all of future events.
- What thresholds should we be working with, 10 was am arbitrary test.
- There is some fairly convoluted code in the paginator that may not make sense for controls that are not date based so `month` is probably the least disruptive unit - though maybe not the best reason to choose it.
 -  Do we want to consider completely rewriting it using `viewComponent` and `stimulus` 
 - Any other outcome we want apart from a larger unit and sensible default on first load?

**Comment by kimadactyl** [comment]
Assuming it's easiest to implement time-based periods. If there's no results, could it possibly have a little "No events in this period, fastforward to the next one" type helper text? (or both these things anyway?)

**Comment by katjam** [comment]
Default to show all events might be the easiest solution?

**Comment by kimadactyl** [comment]
that gets messy with repeating events is the only prob. but yes maybe!

**Comment by ivan-kocienski-gfsc** [comment]
Hmmm, that looks like it'd work (in principle) but could be sped up a bit, as you say.

Maybe another approach would be: find the first 10 events and figure out the gap between [0] and [9], whether it is a day, week, month or longer?

**Comment by ivan-kocienski-gfsc** [comment]
Also just found a similar solution already used in our code [here](https://github.com/geeksforsocialchange/PlaceCal/blob/8fbbe9ca0d0a5aaa5f70805ad3f43122d1554702/app/controllers/partners_controller.rb#L42) for showing upcoming events within a single partner, that may be useful

**Comment by honor-gfsc** [comment]
Noting that regular-flavour PlaceCal sites don't currently have a way to view all future events, nor to set partner pages to display all future events. I would like the option, especially for individual partner pages. For the whole site listings it would be nice to see the next ~10 events, or the next month (or week with high volume?) and to have the default view be configurable. Currently it always displays the current date as default and can be edited to show the next week through a non-obvious menu, month or next-10 or all-future are not viewable.

**Comment by aaaaargZombies** [comment]
OK reading the comments and following a catch up with Rosie the thing that makes most sense is to default to "show all" as Katja suggests, we can then get something working quickly and layer on specific feature requests in additional tickets that can be prioritized appropriately against other tickets in the milestone.

Mountain View will be left in place for now.

**Comment by aaaaargZombies** [comment]
ok implementation basically done, I am noticing that manchester specifically is starting to chug under the load. It's also highlighting the amount of potential dead events we are showing.

## mancheter

with repeating events on
```js
document.querySelectorAll('.event__header').length
6201
```

with repeating off
```js
document.querySelectorAll('.event__header').length
// 51
``` 

Very poor ratio

## trans-dim (london)

repeating on
```js
document.querySelectorAll('.event__header').length
1742 
```

repeating off
```js
document.querySelectorAll('.event__header').length
476 
```

much healthier ratio

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

## Site with few events shows all future events
![Screenshot_2024-04-24_10-09-28](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/406fb29f-a873-4a5c-9bbb-88d66c264e48)

## Site with many events shows regular pagination
![Screenshot_2024-04-24_10-11-33](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/19143cce-215e-40d7-b47e-996d52f1e1eb)
