### ISSUE TITLE
[Bug]: Duplicate neighbourhoods

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2017]
## Description

Because the neighbourhood update script only adds new entries, some neighbourhoods may be "duplicated" (have the same name but differing release dates). 

![Screenshot_2023-08-15_15-04-55](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/d23a8464-c131-4a66-957a-0b6ddfe613ec)

## Steps to reproduce

1. Visit any admin site edit page
2. Start typing a new neighbourhood to bring up the selector
3. Search for "Abbey Road"
4. Duplicate Abbey Road entries appear

## What you expected to happen / Acceptance Criteria

- [ ] For Partner Service Area Neighbourhoods, Site Neighbourhoods and User Neighbourhoods:
  - [ ] Show which neighbourhoods that entity is linked to (legacy or current).
  - [ ] Current neighbourhoods should be displayed as before.
  - [ ] Legacy neighbourhoods should be indicated in some way.
  - [ ] When saving an entity with legacy neighbourhoods, those legacy neighbourhoods should be retained.
  - Neighbourhood picker:
    - [ ] Shows all the latest neighbourhoods as before
    - [ ] Also includes only the legacy neighbourhoods that that entity is linked to
    - [ ] Cannot add "new" legacy neighbourhoods
    - [ ] Can remove legacy neighbourhoods

## Implementation plan / notes

Put a scope on service areas / neighbourhoods to only look at the newest neighbourhoods.

Pages that need to be fixed
- partners edit
    - service areas
- users edit
    - neighbourhoods
- sites edit
   - primary neighbourhood
   - other neighbourhoods
- neighbourhoods index

May need to check the neighbourhood filter on /partners for guest user site partners page.
