### ISSUE TITLE
[epic] Only partner_admins can edit partners details

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2042]
## Description

Give more control of partners to partner_admins, reduce over reach of neighbourhood_admin / partnership_admin powers

## AC

- [ ] must have at least one admin assigned (can't be done in current form) when created (could be creator by default)
- [ ] only partner_admin can edit partner (aside from show on site)
- [ ] any partner_admin can add another partner_admin
- [ ] mechanism for adding user they can't see
- [ ] any and only a partner_admin can delete a partner

**Comment by r-ferrier** [comment]
I agree on this with you but after this morning's meeting think we probably need to get more feedback on what the desired behaviour is here

**Comment by aaaaargZombies** [comment]
## notes from meeting

-  the reason we have the power to edit all the details is in case we need to remove bad/inappropriate info.
- if we have publish/hide state we can then push that responsibility back to the partner admin to address in their own time.
- if we take that action we need to notify (email) the partner admin

**Comment by aaaaargZombies** [comment]
current state:


| property    | read    | update    | is public    |
|---------------- | --------------- | --------------- | --------------- |
| sites visible    | ❌    |  ✅  *   |  ✅   |
| name    | ✅    |  ✅   |  ✅   |
| slug    | ❌    |  ❌   |  ✅   |
| discription    | ✅    |  ✅   |  ✅   |
| accessibility Info    | ✅    |  ✅   |  ✅   |
| image    | ✅    |  ✅   |  ✅   |
| address    | ✅    |  ✅   |  ✅   |
| service areas    | ✅    |  ✅   |  ✅   |
| address    | ✅    |  ✅   |  ✅   |
| public contact info    | ✅    |  ✅   |  ✅   |
| partnership contact info    | ✅    |  ✅   |  ❌   |
| tags    | ✅    |  ✅   |  ✅   |
| connected calendars    | ✅    |  ✅   |  ✅   |
| partner admins (users)    | ✅    |  ✅   |  ❌   |

*via address /service area

**Comment by kimadactyl** [comment]
I foundationally disagree with the title of this ticket and think the AC are a bit of a hodgepodge. Closing as won'tfix, let's open more specific issues if we want to revisit this stuff.
