### ISSUE TITLE
Create opengraph preview images

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2077]
## User story

As someone sharing data on PlaceCal with a friend, I want to see information in the preview image when I paste a link in environments that support open graph preview.

I think not having this is making us look a little old fashioned and it may be a barrier to widespread adoption. The current og image is used on every page including the admin and it looks a bit clunky.

## Acceptance criteria

- [ ] A guideline image template is created we are all happy with
- [ ] Partners preview images contain information about the partner
- [ ] Site home page preview images contain information about the site
- [ ] Event preview images contain information about the event
- [ ] Admin pages don't have an OG image any more (keeps cluttering up when we post in discord)

## Implementation notes & questions

Various tutorials for this come up on Google

* https://dev.to/matiascarpintini/how-to-generate-og-links-preview-like-devto-for-free-with-rails-7-57b2
* https://dev.to/aablinov/open-graph-image-generation-on-the-fly-with-ruby-48o4

## Implementation plan

_To be written by the developer_
