### ISSUE TITLE
[Draft Epic]: PlaceCal v1.0 MVP

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2086]
# Overview

A ticket to track our status releasing PlaceCal v1.0. This work will be completed across multiple milestones and tickets and this aims to keep an overview of the project. This ticket is to focus on the absolute have to haves -- let's focus on making what we have right now work reliably and well.

Overall this core funcionality is all reviewing the basic create, read, update and delete commands for our 3 current user groups  and making sure they're all watertight and nice to use (citizens, partners, and organisers)

This kind of ticket might be a terrible idea but I think i prefer to keep this thinking in the repo and not notion.

## Overall

- [ ] No broken or incorrect links in interface anywhere
- [ ] Security sweep for leaky data
- [ ] Update to Rails latest and fix all renovate stuff
- [ ] README.md easily gets you to a state a member of the public can develop from

## Citizens

- [ ] Citizens can filter, sort and search for events in their area or by their interest (i think we should rip out the jquery stuff there now in favour of hotwire stuff)
- [ ] Data is well formed for ld+json etc
- [ ] Accessibility sweep on frontend (we need to do this for admins too but i think lower prio)
- [ ] You can find out who to contact if things go wrong

## Partners

- [ ] Have a reasonable onboarding experience
- [ ] Partner admins have appropriate access rights (Make a ticket for partner admin access rights)
- [ ] It is clear what happens with your data once added
- [ ] We get regular (regular can mean bimonthly, just you know, at all) confirmation that listings are still up to date (i think this is the email notifs MVP)

## Organisers / Commissioners

For now these are the same thing - lets make both work to a minimum standard first, and look at commissioner-specific rights later on.

- [ ] Organisers have appropriate access rights (#2063)
- [ ] Organisers can do some customisation / personalisation of their site pages without our input
- [ ] Organisers can do filtering and sorting on partners on key fields for e.g. seeing ones where there's no events, no category, thngs in one given ward (e.g. rip out datatables)

## Bonus features

Low hanging fruit that could be seen as part of getting wider adoption of the idea as a whole but are deffo not 100% needed technically:

- [ ] Provide code for a basic embed for partners to use on their website - i think this would be a huge sell to get them on board
- [ ] Create a trans dim boilerplate

**Comment by ivan-kocienski-gfsc** [comment]
Looks good! I agree this is more helpful in github as that is where the code is.

Just a couple of small points
* Upgrade to ruby 3.x
* Are you calling Citizens users who are visiting the public site? (we already use that term in the admin side of things to designate someone who is not root or not and editor)

The rest seems okay. Guess we'll be working through christmas at this rate ;)

**Comment by kimadactyl** [comment]
Yep sounds good to 3.0, we should be up to date with latest everything right.

And yes to citizens. If confusing can change. But my idea was to never refer to an abstract user but rather you know, an idea of who the person actually is, in this case a resident of somewhere or a fan of an interest.

And yeah dw i think this will prob take us closer to May!
