### ISSUE TITLE
Make it clear where partners can go for help with tech problems

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#2146]
## User story

As a person running into problems setting up a new calendar or organisation, or feeling something is not quite right, I need to know the paths to common fixes and when to call for help.

Raised off the back of #2094 

## Acceptance Criteria

- [ ] on each page of the admin UI non-root users can access the following:
  - [ ] Link to handbook
  - [ ] Link to support email
  - [ ] Link to Discord
  - [ ] Link to report a bug on Github

## implementation plan

based off Kim and Ivan's suggestions I think we should make use of the sidebar nav to have help available on each page.

For non-root users we can use the space of "In development" and assume that root users are the people who would be giving the help or at least already know how to find resources.

![image](https://github.com/geeksforsocialchange/PlaceCal/assets/6824891/8117860b-9838-46a1-b371-08adbef415e2)

**Comment by kimadactyl** [comment]
Could literally just be a link to the handbook and a link to the discord in a nice big box on the dashboard index?

**Comment by ivan-kocienski-gfsc** [comment]
Hmmm. That does sound good - 

Possible approaches:
- Have one help button on the title bar / main nav that links to a handbook page for the entire admin interface (least code effort)
- Have a help button on each page that links to a page in the handbook that covers that part only
- Have lots of small "help" buttons throughout next to various things (like the calendar strategy picker) that explains those specific parts.

**Comment by ivan-kocienski-gfsc** [comment]
If we are going with the second option then:

The A/C would be help pages and links for
- [ ] Logging in page (overkill?)
- [ ] Dashboard
- [ ] Partners index and new/edit
- [ ] Calendars index and new/edit
- [ ] Users index and new/edit
- [ ] Sites index, show and new/edit
- [ ] Tags index and new/edit

Things non-root people should be hidden from:
- Articles
- Collections
- Supporters
- Importer status (although this may be useful for internal documentation)

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging (although the email address is not a link?)

## See "GET SUPPORT" section in side panel

![Screenshot_2024-04-24_10-31-28](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/9b4dc4d1-7d5a-4839-a409-26645d5c2b21)
