### ISSUE TITLE
List and review gems used

### ISSUE THREAD

**Issue by ivan-kocienski-gfsc** [geeksforsocialchange/PlaceCal#2159]
## Description

What gems do we use? What do they do? Can we drop some?

(Bonus: are there updates, are they obsolete?)

## A/C

- [x] list of gems (with descriptions)
  - [x] are they used?
  - [x] are they obsolete?

## Tasks
- [x] #2162
- [x] Look at EOL (not had a release in the last two years) gems and see what (if anything) can be done
  - [x] sass-rails - #1319 
  - [x] ajax-datatables-rails
  - [x] eventbrite_sdk (??!)
  - [x] httparty
  - [x] image_processing
  - [x] cocoon
  - [x] font_awesome_rails
  - [x] select2_rails
  - [x] mountain_view
  - [x] kramdown
  - [x] active_link_to
  - [x] sendgrid_actionmailer
  - [x] uk_postocde
  - [x] dotenv_rails
  - [x] letter_opener
  - [x] rails-erd
  - [x] rubocop-rake
  - [x] capybara_select2
  - [x] graphql-client
  - [x] json_matchers
  - [x] minitest-rails-capybara
  - [x] rails-controller-testing

**Comment by ivan-kocienski-gfsc** [comment]
Have produced a table [here](https://docs.google.com/spreadsheets/d/14HGGY2KqcZkH8Rb8lGtVWXIg5yyj_TBzgVJkMB4z5oA/edit?usp=sharing) that covers all the gems, whether they are used, whether they are obsolete

**Comment by r-ferrier** [comment]
Gems that still appear to be stable:

- ajax-datatables-rails - https://github.com/jbox-web/ajax-datatables-rails - last updated 4 months ago and compatible with rails 7.1
- eventbrite_sdk - part of eventbrite's official stable of plugins, (https://github.com/eventbrite/eventbrite-sdk-ruby) no recent code changes but repo updated within the last year, so looks good to me
- httparty - https://github.com/jnunemaker/httparty - code updated last week
- image_processing - [still b](https://github.com/janko/image_processing) - code updated within last year
- cocoon - still going strong - https://github.com/nathanvda/cocoon
- font_awesome_rails - https://github.com/bokmann/font-awesome-rails - last updated 4 months ago
- kramdown - https://github.com/gettalong/kramdown - owner still responding to issues and looks stable
- uk_postcode - https://github.com/threedaymonk/uk_postcode - not updated in a long time but stable and not checking against active data
- dotenv_rails - https://github.com/bkeepers/dotenv - updated last month
- letter_opener - https://github.com/ryanb/letter_opener - updated last week
- rails-erd - https://github.com/voormedia/rails-erd - updated within the last year and non-essential
- rubocop-rake - https://github.com/rubocop/rubocop-rake - updated 4 months ago
- capybara_select2 -  https://github.com/Hirurg103/capybara_select2 - not updated for 2 years but seems stable. only used for testing.
- graphql-client  - https://github.com/github-community-projects/graphql-client - updated last week
- json_matchers - https://github.com/thoughtbot/json_matchers - very out of date BUT only used for testing
- minitest-rails-capybara - https://github.com/blowmage/minitest-rails-capybara - same as above

Bad gems:

- active_link_to - [active_link_to](https://github.com/comfy/active_link_to)
- select2_rails https://github.com/argerim/select2-rails/issues/202
- sendgrid_actionmailer  - https://github.com/eddiezane/sendgrid-actionmaile
- rails-controller-testing - https://github.com/rails/rails-controller-testing

**Comment by r-ferrier** [comment]
I've reticketed everything that I think needs attention and made notes on everything else. Closing as complete!
