### ISSUE TITLE
Partners have separate facility, partnership and category inputs

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/PlaceCal#2333]
## description

It is hard to explain to organizers why there are different types of tags and they all live in the same input, there is discussion in this pr  #2320 about #2066

It has been decided that the priority is to try and split out the partners tag inputs into separate fields.

## AC

- [ ] there is an input for category tags 
- [ ] category input has validation for max 3 selected
- [ ] there is an input for partnerships 
- [ ] partnership input has JS validation that warns a user about removing a tag from a partner
- [ ] there is an input for facility tags

## implementation plan

Investigate if it is possible to leave partners with a `tags` relationship and just update the inputs.

If not restructure all the places tags are checked on partners.

**Comment by kimadactyl** [comment]
Yeah just to reiterate this is the most important one, the rest are kinda do once and forget about it things.

The big thing here is that if the categories are laid out as checkboxes i think people are far more likely to use them than they are now.

Also, most people will just have 1 partnership if they have any at all and making this as absolutely easy to click as possible would be great. Tbh ideally it would be pre-seleted if people only have 1 partnership but aware im stretching the spec here.

**Comment by katjam** [comment]
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ad01f56b-f87c-49ef-933e-0781fa407f19)

**Comment by katjam** [comment]
Verified on staging.

Validation for max 3 category tags:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/1ee4846a-c426-472e-bb9b-fe1b65cdcbd9)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/c91fee29-620c-498c-9484-9cd0427c5947)

**Comment by katjam** [comment]
Warning for removal of partnership tag
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/a0474fac-b183-4538-83be-40c605a03f4f)

@honor-gfsc This one might want a copy simplification if you have time.

**Comment by honor-gfsc** [comment]
Whew this sure says partner a lot. Suggest:

> Removing this tag will remove this partner from your partnership. This means you will no longer have access to this partner, or any users that are only assigned as admins for this partner.
