### ISSUE TITLE
Log who created and last updated partners and users

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2371]
## User story

As PHT, we need some basic record keeping about who created partners and users in order that if there's any kind of incident we can work out who we need to talk to about it.

As an organiser, I want to be able to see who has created and edited partners in my partnerships, in order that I can work with that person instead of cross purposes.

_Created as part of the [cycle 29 scoping workshop](https://www.notion.so/gfsc/Scoping-PlaceCal-Accuracy-Reliability-Consent-cycle-d04f48d75fd84acfbf3b9b9bdaca86db?pvs=4)_

## Acceptance criteria

- [ ] Partners store which user created them, and when
- [ ] Users store which user created them, and when
- [ ] Partner creation and last updated info is visible in the admin interface to anyone who can view the partner
- [ ] User creation and last updated info is visible in the admin interface to anyone who can view the user
- [ ] Deleting the user that created a partner or user doesn't case everything to break

## Implementation notes & questions

Previously I think we were tracking this with the `paper_trail` gem.

This is being done as a stopgap until we can resolve this fully https://github.com/geeksforsocialchange/PlaceCal/issues/2256

## Implementation plan

_To be written by the developer_

**Comment by ivan-kocienski-gfsc** [comment]
Seems like [this](https://stackoverflow.com/questions/9835863/log-user-activities-in-ror) approach may be helpful here.

Create a model `ActivityLog` that stores the actions (create, modify, (delete?)) and then "log" activity in the controller.

Root users can then pull up a Partner, Calendar, Site etc. and see who did what when.

**Comment by kimadactyl** [comment]
Hmmm that sounds like a lot of interface to me compared to adding fields to our existing models? I do like it though that makes a lot of sense. Just sounds like a load of work.

Another option would be to just use `Rails.logger` to just make a regular text log file?

**Comment by katjam** [comment]
This probably needs a couple of heads together to come up with a minimal effort set of first steps AC. The use case that has come up most recently is for a partnership admin to be able to see a list of the partners they recently added, so the text logs wouldn't be sufficient. If we wanted to implement this for infosec compliance then we'd probably need to work out a comprehensive & consistent  logging strategy and to implement log rotation on server or they'd fill up pretty fast.

So, we maybe need to get back to considering what the actual urgent problem is that we are trying to solve.

**Comment by kimadactyl** [comment]
OK I think roughly in order for me:

* As PHT, we need some logs of who is adding people in case a partner gets funny with us and we need to work out what happened (i.e. so we can fulfill our duties under privacy / tos). Or if a partner turns out to be nasty/bad and we need to remove them, which will require knowing who added them so we can address it properly.
* As PHT, we need to see who is active and adding partners so we can support them properly reviewing them as they go up (checking for new calendar formats, checking for errors and seeing how people are using it, stuff like that)
* As organisers, they need to not be working cross purposes and see if someone else is editing partners that are in more than one partnerships (i.e. prevent people having an edit battle without realising, or worse have things edited without them realising)
* As organisers, it's really helpful to see if a partner themself has made the changes or another organiser

**Comment by katjam** [comment]
It's too late in the day to do any new feature - but as an minimum we could log out messages on create and edit of whichever models we care most about (partner?).

`Partner [id] created by User [id]`

This seems the most minimal thing we could do to at least have a record that we can look at if we need to - but it also feels like the least useful to our users.

**Comment by ivan-kocienski-gfsc** [comment]
Dokku wraps Rails in a stateless container so logging is not written to a file but handled by dokku (plugins?) or a third party log persistence facility

See [the docs](https://dokku.com/docs/deployment/logs/).
