### ISSUE TITLE
Show the last time a calendar's data was updated

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2373]
## User story

As an organiser, I want to see when calendars were last updated by the partners (i.e, when events were last added or edited at the source level), in order that I can identify who hasn't updated them for a long time and know which listings are fresh

_Generated at [Cycle 29 scoping](https://www.notion.so/gfsc/Scoping-PlaceCal-Accuracy-Reliability-Consent-cycle-d04f48d75fd84acfbf3b9b9bdaca86db?pvs=4)_

## AC

- [ ] I can see the date my calendar was last updated in the calendar status section
- [ ] On the calendar status, if it was last updated more than 6? months ago, I can see a warning asking me if it is current
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/a5e7d5dd-40a4-489d-aaa5-cc4d9f4559d2)
- [ ] On the calendar index page, the last updated field shows the time of checksum, not when the calendar was saved
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/804d05f8-5dcc-48fd-a39f-f5ee94316486)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/ac779d75-c48e-4e5a-8fba-2434e2110328)

## desirable outcomes pending research

- [ ] Calendars show the last time the source data was changed (where possible)
- [ ] It's possible to view this information in the calendars index and show pages
- [ ] We clean up the nomenclature a bit - the current "last updated" probably refers to when the model was last modified, not when the source data was changed
 
## Implementation notes & questions

Note this is probably quite complex and source-dependant. I think some functionality is better than none. We can do based on the hash of the input changing, on the last non-repeating event, etc.

Our current approach is to spawn repeating events up to a year in advance.

## Implementation plan

- add date of checksum to modal and record when we update.
- seperate out completion of importer and updating of checksum
- prevent attempts to hash `nil` on failed `download_calendar`
- sanatize ical feeds
- surface this info on admin UI

re-ticket as not essential for AC

- ignore unused feeds for now, open techdebt tickets to ensure they meet the same standard as the above tested sources.
- ideally on index and allow sort by date so stale calendars can be weeded out.
- should probably handle checksums on a per parser basis in case there's sources that aren't capable of producing usable checksums
- there should be a method of communicating if a parser has a valid method for generating a checksum

**Comment by aaaaargZombies** [comment]
Potential angles

- Katja thinks there may be meta data on the feed we can scrape
- last date of non-repeating event / does it have any non-repeating events

**Comment by aaaaargZombies** [comment]
## checksums usefulness

### google ical
```sh
$ curl https://calendar.google.com/calendar/ical/c_3bb14358226dac945a0a806f0a98389a353a2e26ec023d1e3a49f52ef874fe9f%40group.calendar.google.com/public/basic.ics | md5sum 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2899    0  2899    0     0   7002      0 --:--:-- --:--:-- --:--:--  7019
1b4fc693ace9bf34fe7ac4a42a256f8a  -
$ curl https://calendar.google.com/calendar/ical/c_3bb14358226dac945a0a806f0a98389a353a2e26ec023d1e3a49f52ef874fe9f%40group.calendar.google.com/public/basic.ics | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2899    0  2899    0     0   6869      0 --:--:-- --:--:-- --:--:--  6885
6c4a7ace89ed0e24c5a8b5de415fdca1  -
$ curl https://calendar.google.com/calendar/ical/c_3bb14358226dac945a0a806f0a98389a353a2e26ec023d1e3a49f52ef874fe9f%40group.calendar.google.com/public/basic.ics | md5sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2899    0  2899    0     0   7267      0 --:--:-- --:--:-- --:--:--  7283
61d1623499bfb84e6386c5c8ad8f0ab4  -
```

not looking great

digging into the files it looks like this is the issue

```
DTSTAMP:20240418T114516Z
DTSTAMP:20240418T114521Z
```

Both from the same event, probably the time this was generated / requested.

```
LAST-MODIFIED:20240403T094815Z
```

There is this field which looks useful as Katja suggested. It is per event.

**Comment by aaaaargZombies** [comment]
### xml

todo

**Comment by aaaaargZombies** [comment]
### squarespace

todo

**Comment by aaaaargZombies** [comment]
### manchester uni

todo

**Comment by aaaaargZombies** [comment]
### check other ical sources as very common import

```sh
#!/usr/bin/env bash

feeds=(	"http://p24-calendars.icloud.com/published/2/WvhkIr4F3oBQrToPU-lkO6WwDTpzNTpENs-Qtbo48FhhrAfDp3gkIal2XPd5eUVO0LLERrehetRzj43c6zvbotf9_DNI6heKXBejvAkz8JQ"
"https://ics.teamup.com/feed/ksq8ayp7mw5mhb193x/5941140.ics"
"https://outlook.live.com/owa/calendar/1c816fe0-358f-4712-9b0f-0265edacde57/8306ff62-3b76-4ad5-8dbe-db435bfea444/cid-536CE5C17F8CF3C2/calendar.ics"
"https://www.birchcommunitycentre.co.uk/events.ics"
"https://dalstonsuperstore.com/events/?ical=1"
"https://www.heartoftorbaycic.com/events/feed/"
"http://mossleycommunitycentre.org.uk/events.ics"
"https://calendar.google.com/calendar/ical/krn443cu280kf6et8qr8h30kgg%40group.calendar.google.com/public/basic.ics"
"http://spectra-london.org.uk/?post_type=tribe_events&tribe-bar-date=2022-04-17&ical=1"
)

for item in "${feeds[@]}"; do
	echo "$item" >> log.txt
	for Variable in {1..5};do
		hash=$(curl "$item" | sed  | md5sum)
		echo "$hash" >> log.txt
	done
done
```

They all look like they hash well except the google one and we know how to sanatize that so this looks viable

https://gist.github.com/aaaaargZombies/8780542e4a8293ab2f63ac897557ecb0

**Comment by aaaaargZombies** [comment]
## proposal

- add date of checksum to modal and record when we update.
- seperate out completion of importer and updating of checksum
- handle failing network requests so they at least don't interfere with hashing (there is talk elsewhere of gracefully recovering but that is outside scope of this ticket)
- sanatize ical feeds
- ignore unused feeds for now, open techdebt tickets to ensure they meet the same standard as tests sources.
- surface this info on calander form view
- ideally surface on index and allow sort by date so stale calendars can be weeded out.



I still think it would be valuable to surface which feeds are repeat events only too, this should be a less involved and be a boolean state to represent to the organizers.

**Comment by katjam** [comment]
This all looks good. maybe since we are late in the cycle, maybe do the 1st 3 steps and re-ticket the rest? I'll amend the AC now.

**Comment by ivan-kocienski-gfsc** [comment]
Verified on staging

![Screenshot_2024-04-24_15-40-55](https://github.com/geeksforsocialchange/PlaceCal/assets/109223824/82289122-2fcb-4b3d-84c0-4512b8af9b18)
