### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2397]
Draft here: https://www.notion.so/gfsc/PlaceCal-Privacy-Policy-2a8aeef755a64fbdba77d8bac3b0f985?pvs=4

## Acceptance criteria
- [ ] There is a privacy policy linked from the footer
- [ ] The privacy policy reflects accurately what we do

# Implementation plan

- [ ] Dev team sign off draft
- [ ] Content team sign off draft
- [ ] Add link to site footer
- [ ] Add new page for it

**Comment by katjam** [comment]
This is good to be added as per the draft with `[cCc]` for verification in places where something seems off or incomplete. Let's get the page up and revisit when we come to verifying.

**Comment by katjam** [comment]
Verified on staging:
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/f88cae88-46a5-4adc-b5e0-8a93ef9a0c69)
![image](https://github.com/geeksforsocialchange/PlaceCal/assets/861172/51915dd7-0824-4d0e-b589-08d16befc068)

linked: https://placecal-staging.org/privacy
