### ISSUE TITLE
Improve our open graph previews

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2491]
## User story

Currently, our OG data is a bit all over the place, the defaults are being used in way more places than they should be, site images are not being used over the default one, for example. I think this just looks a bit scuffed basically and with a bit of polish it'll look a lot more professional.

While https://github.com/geeksforsocialchange/PlaceCal/issues/2077 is a bit out of reach for now it would be nice to somewhat polish this so at least the OG text matches the page title and the like.

## Acceptance criteria

- [ ] Overall goal: **all citizen-facing PlaceCal pages have sensible OG/metadata settings**
- [ ] Set site tagline as site home, event and partner index description
- [ ] Set partner summary as partner description
- [ ] Set event description as event description
- [ ] og:images are correct dimensions where possible (1200x600)
- [ ] Set hero image as og:image, if set, on site home index
- [ ] Set hero image as og:image, if set, on site partner index
- [ ] Set hero image as og:image, if set, on site event index
- [ ] Set partner logo as og:image, if set, on site partner show page 
- [ ] Set partner logo as og:image, if set, on site event pages
- [ ] Remove refs to "in your area" and other text (holdover from when we were soley a location-based service)
- [ ] Canonical / meta URLs are the full instance URL to the page
- [ ] Add rake task to regenerate og:images

## Implementation notes & questions

Note images will need to be regenerated after update, docs here: https://github.com/carrierwaveuploader/carrierwave?tab=readme-ov-file#recreating-versions

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
One justification for working on this now we are rolling out is that often the OG image is the first impression someone has of the website. Weird how things change!

**Comment by katjam** [comment]
Your acceptance criteria read more like an implementation plan. The AC would be like:

- [ ] When I share a partner that has all meta fields defined, on twitter: I can the partner's card image, title and a description that is specific to that partner.
- [ ] When I share a partner that has not defined any meta fields, on twitter: I see the default site image, site title and site description.
- [ ] etc...

**Comment by kimadactyl** [comment]
ahh i see yeah i was struggling to know how to break this down as its all a bit twisted and easier to think about one rule as a time, i did originally have it drafted more like that but it was confusing me! i think thinking about the screenshot makes a lot of sense
