### ISSUE TITLE
Migrate remaining icons into SVG helper class

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2517]
## User story

We have some [icons in an iconfont](https://github.com/geeksforsocialchange/PlaceCal/pull/2485) and some loaded directly with the filesystem. Icons loaded one at a time are slow, and this gives two places to maintain.

Instead we should have all icons loaded through the iconfont.

## Acceptance criteria

- [ ] All icons are moved into SVG helper class
- [ ] Site updated to use icons
- [ ] Remove `.icon-font` classes, just one icon css class please
- [ ] Consider moving over main site logos and other SVG assets too
- [ ] Remove refs to fontello and other config from the repo

## Implementation notes & questions

Some SVGs are complaning and we need a little attention before we can begin.

To see the issues:

1. Go to https://fontello.com/
2. Drag in contents of [icon directory](https://github.com/geeksforsocialchange/PlaceCal/tree/main/app/assets/images/icons)
3. Observe errors from mousing over

<img width="1464" src="https://github.com/geeksforsocialchange/PlaceCal/assets/511734/b26e80bb-ff36-4b23-b990-3b208413d448" alt="Screenshot 2024-06-25 at 12 06 57">

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
yeah thats a good idea and i think can be even simpler - just run a type check in the icon method for a simple icon (string) or complex one (hash) and run a diff method depending?

**Comment by kimadactyl** [comment]
i think it doesn't need to be in this repo if it's a one-off task. honestly ive been using Claude for that kinda thing - its very good with that kinda grunt work. happy to host it on gfsc github if you do want to make a tiny utility! i guess itll come in handy if we get more assets from designers that are not normalised to the same dimensions?
