### ISSUE TITLE
Move API code examples inside codebase

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2520]
## User story

As a developer I want an easy way to test the API, and I want the API examples to remain inside the codebase so they stay up to date.

## Acceptance criteria

- [ ] API examples from the handbook are in the codebase
- [ ] Requests generated by [Trans Dimension are documented](https://github.com/GenderedIntelligence/the-trans-dimension/tree/main/src/Data/PlaceCal) and have minimal testing
- [ ] README updated to show how to run them
- [ ] Handbook updated to point to the Bruno examples

## Implementation notes & questions

Plan is to use [Bruno](https://www.usebruno.com/) for this.

## Implementation plan

_To be written by the developer_
