### ISSUE TITLE
Allow partners to list other partners as their location

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2522]
## User story

As a partner using a community centre or similar venue for all my events, I want to be able to list that partner as my location in order that:

- If there is a venue calendar for the whole place it can be linked to, wheras currently we have no easy way to manage calendars for people whose canonical event source is in a venue listing
- Reduce duplicate information storage
- Help people find other partners at the same venue
- If the venue moves or changes its info, it only has to be done in one place

## Acceptance criteria

- [ ] As a partner, I can set another partner as my location
- [ ] As a venue used by other people, I can allow other people to see what partners use my venue
- [ ] As a guest, I can see all the partners that use a given venue
- [ ] As a guest looking at a partner without its calendar but whose events are listed on a venue calendar, I get some kind of notification to try checking there

## Implementation notes & questions

This could adopt the half-implemented object relation system #1216

## Implementation plan

_To be written by the developer_
