### ISSUE TITLE
Support webp images where appropriate

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2539]
## Use case

Webp is a more "modern" image format - we should support it

## Acceptance criteria

- [ ] Partner images can be webp
- [ ] Site headers can be webp
- [ ] Site logos can be webp

## Implementation plan

_To be written by the developer_
