### ISSUE TITLE
Add Appsignal & possibly remove Rollbar

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2547]
## Use case

I've been having a look at the[ codebase for the government epetitions website](https://github.com/alphagov/e-petitions/tree/master) to learn some tricks and see they are using this service [Appsignal](https://www.appsignal.com/) which looks excellent. I've never loved rollbar, I don't think it helps with bug triage at all really, and this looks like a nice drop in alternative.

It seems like pure upside:

- Most notably, it has a free open source package so we'd no longer be fighting rate limits.
- It also has a GUI for logging, which will really help as currently you need to go into dokku for this. Also it means when we add better CRUD creation logs, we have our data log done.
- We don't have any monitoring for expensive processes atm - this looks like it has it in spades
- It's specifically targetting Rails and really understands the underlying system - rollbar is very generic

To me this just looks like a pure upgrade.

## Acceptance criteria

- [x] Get a free open source account
- [x] Add Appsignal
- [x] Remove rollbar when we've agreed it's surplus to requirements

## Implementation plan

- [x] Install gem and get token
- [x] Add env var to staging
- [x] Add env var to prod
- [x] Test on staging
- [x] Remove rollbar
- [x] Deploy to prod
- [x] Test on prod

**Comment by katjam** [comment]
Doesn't sound like a bad idea. Could be done outside a sprint, in isolation (by volunteer?)

**Comment by kimadactyl** [comment]
i think its gonna be one of those waiting for emails/2fa/saas login hell tickets sadly! ill get it up on staging at least

**Comment by katjam** [comment]
Do we want to leave this open while we test on staging and then generate the ticket to implement live?

**Comment by kimadactyl** [comment]
Yep good call

**Comment by kimadactyl** [comment]
<img width="1233" alt="Screenshot 2024-09-02 at 18 57 53" src="https://github.com/user-attachments/assets/85e5bc48-5884-4b1c-8053-bcfb0499510d">

appsignal deploy markers working
