### ISSUE TITLE
Make it easy to set up live servers, probably using Kamal

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2627]
## User story

As a developer, I want to be able to easily set up and tear down test servers so I can have my own testing environment and we are not so shackled to GFSC's staging server.

Dokku is what's currently described in our INSTALL.md and this felt state of the art in 2017 when we were getting going but there's now probably better things, most notably Kamal which is created by the Rails team.

@lenikadali shared some thoughts here: https://gist.github.com/lenikadali/d76147db5fc5e9e4c037d84638cd0930?permalink_comment_id=5240007#gistcomment-5240007

## Acceptance criteria

- [ ] You can run one (or a small number) of commands to get a PlaceCal server up and running
- [ ] You can run one (or a small number) of commands to strike down the PlaceCal server
- [ ] Optional: PlaceCal `main` branch is reconfigured to use this new method
- [ ] Optional: PlaceCal `production` branch is reconfigured to use this new method

## Implementation plan

_To be written by the developer_
