### ISSUE TITLE
Add Instagram to API endpoints

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#2654]
## User story

As a Trans Dim developer, I want to have access to Instagram data, as many groups use this as their primary web presence, in order that people can find and access these groups

## Acceptance criteria

- [x] All partners endpoint has instagram
- [x] One partner endpoint has instagram
- [x] Bruno examples are updated

## Implementation plan

_To be written by the developer_

<sub><a href="https://huly.app/guest/geeksforsocialchange?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU1YWUwZDFlMDYzMmRkMDhlMjU4YTMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Incta2ltLWdlZWtzZm9yc29jaS02NzFlNzVmOS03ZTVlMTU1YzMwLTIxZjkwZCJ9.hyEqLf84Mo_RwSgrcgDf2XkS3ENZrWJc6e2JwN6IU0k">Huly&reg;: <b>PC-2661</b></a></sub>
