### ISSUE TITLE
Epic: Add a news system

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#813]
**Is your feature request related to a problem? Please describe.**

Partners, Neighbourhood admins and Site Admins want to be able to post news about their group, area or site respectively.

## Minimum

- [x] #957
- [x] #960
- [x] #961
- [x] #962

## Adding specificity

_Flesh these out when we get here_

- [x] #814
- [x] #1101
- [x] #1108
- [x] Decide how to handle teaser text
- [x] #1120
- [x] #1116

## Acceptance critera

_Don't make tickets for these, they're to be checked off by a human!_

- [x] I can upload an image to a news article
- [x] I can set the author for a news article
- [x] Articles can be given tags in the article edit interface
- [x] I can get a list of The Trans Dimension news from the API with a tag filter

**Comment by kimadactyl** [comment]
Note to self to add acceptance criteria to this ticket

**Comment by kimadactyl** [comment]
I removed tag and neighbourhood links from this because thinking on it more we can make do with sites and partners for a really long time :)

**Comment by alexandria-gfsc** [comment]
Ok so I think things that are left on this epic:

- Add an author field to news articles
- Add an image field to news articles (16:9, 636 x 357 on screen)
- A datatables types ticket to resolve `['Gendered Intelligence']` showing up in the index

Am I missing anything? I don't think any of these are defined though

**Comment by kimadactyl** [comment]
Yep, have added to ticket. Third one can wait :)

**Comment by kimadactyl** [comment]
Teaser text we will just do as a frontend truncate
