### ISSUE TITLE
Add global directory of partners & events on main site

### ISSUE THREAD

**Issue by katjam** [geeksforsocialchange/PlaceCal#848]
## User story

As a citizen, I want to be able to see what partners, partnerships and places are available to browse on PlaceCal without needing to load a local site, in order that I can find information relevant to me and my area

## Acceptance criteria

- [ ] The default site clearly explains what kinds of information there is on PlaceCal
- [ ] The default site has a global partnership (tag) listing
- [ ] The default site has a global partner listing
- [ ] The default site has a central locations directory
- [ ] Partners have a global listing that links to their subsites
- [ ] Partnerships have a global listing that links to their subsite
- [ ] Locations are browsable so you can see where people are
- [ ] The sales stuff is moved somewhere else?

## Implementation notes & questions

[Design work in progress here](https://design.penpot.app/#/view/f0ef25f0-fafc-11ec-8f45-75f6b8214121?page-id=f0ef25f1-fafc-11ec-8f45-75f6b8214121&section=interactions&index=0&share-id=5271bf00-fb7e-11ec-8f45-75f6b8214121)

## Implementation plan

_To be written by the developer_

**Comment by kimadactyl** [comment]
Closing in favour of #2978 which covers the same feature with a detailed implementation plan. The Penpot design link from this issue may still be relevant — see https://design.penpot.app/#/view/f0ef25f0-fafc-11ec-8f45-75f6b8214121?page-id=f0ef25f1-fafc-11ec-8f45-75f6b8214121&section=interactions&index=0&share-id=5271bf00-fb7e-11ec-8f45-75f6b8214121
