### ISSUE TITLE
Epic: Make a "London" PlaceCal site for TransDim testing and "GM Systems Changers" site

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#857]
We need somewhere for partner and event info to show up while testing while we get data in the right format.

- [x] Set up a London site on staging (not visible in public directory)
- [x] Document how to create it (think this isn't written down anywhere right now) including: hero image, colour scheme, letsencrypt, possibly plausible code, etc
- [x] #898
- [x] When Ivan's coccoon thing is done, create a new tag and push to prod
- [x] Add a few partners and create site on prod
- [x] #884
- [x] #885
- [x] Repeat the above but for `gmsc`
- [x] Fix placecal logos and header images on prod
- [x] #922

**Comment by kimadactyl** [comment]
So previously this had a bug where once Primary Neighbourhood is set it really hates being changed.

If you select a Secondary Neighbourhood that is the same as the Primary Neighbourhood the whole thing 501s and we never quite worked out why

**Comment by alexandria-gfsc** [comment]
Wasn't sure what Partners to add for GMSC, and we'll have to wait for the hotfix for `/partners` to be tagged and go through to production for them to be visible, but the sites have been created, so I'm closing this (we can reopen it later if necessary).
