### ISSUE TITLE
Add JavaScript testing

### ISSUE THREAD

**Issue by kimadactyl** [geeksforsocialchange/PlaceCal#870]
## User story

As a PlaceCal developer, I need frontend testing, in order that I can test our JavaScript sprinkles stay working, so we don't get unexpected functionality dying

## Acceptance criteria

- [x] We have a new test folder for javascript tests
- [x] We have a minimal test example working ('hello world')
- [x] We don't have to change our current integration tests
- [ ] verify system tests run on other developers machines (node setup, browser install)

## Implementation notes & questions

- Assume Capybara for this but are there options e.g. Jest?
- What driver shall we use?
- How will this affect performance? 
- We will need to update the [CI test command if we use rails system tests](https://guides.rubyonrails.org/testing.html#system-testing)

## Implementation plan

- [x] look at js testing in rails
- [ ] selecting a test framework write a sample test to make sure application is testable
- [ ] make a high level enumeration of JS that needs to be tested, pick points that are most critical to core PC functionality and write tests
- [x] set up system tests as part of CI/CD pipeline

**Comment by ivankocienski** [comment]
I am assuming this works now on peoples machines.

**Comment by kimadactyl** [comment]
If it doesn't will re-open, but as long as two people got it working I'm sure it's fine!

**Comment by katjam** [comment]
Verified by @alexandria-gfsc, @ivankocienski and @aaaaargZombies on their machines. :( My local is borked - but will report back if these tests don't work once it's fixed.
